### ISSUE TITLE
.contains() only yields first match

### ISSUE THREAD

**Issue by fineline** [cypress-io/cypress#1009]
- Operating System: Mac 10.12.6
- Cypress Version: 1.1.2
- Browser Version: Chrome 62.0.3202.94

### Is this a Feature or Bug?

BUG

### How to reproduce:

In a page with multiple spans containing the text "Test", issue the following:

```javascript
cy.contains("Test").then((results) => {
  debugger
})
```

When the dev tools stops at the debugger line, inspect results. 

### Current behavior:

It contains a single element.

### Desired behavior:

Documentation here:
https://docs.cypress.io/api/commands/contains.html#Content

states:
.contains() yields the new DOM element(s) it found.

It seems it only yields a single element, but should yield them all.

**Comment by jennifer-shehane** [comment]
This is in fact an error with the documentation. .contains() always yields the first *element* containing the text (also with regard taken to find relevant elements over deepest). The yields statement should be updated to:

> .contains() yields the new DOM element it found.

If you have a particular use case for having a command in Cypress that yields multiple elements with the containing text, please specify an example and your need so that we can consider adding it as a new feature.

**Comment by brian-mann** [comment]
All of the rest of the `contains` documentation states everywhere that it yields the first element. I guess you pointed out the one place where it conflicts with that. It's because those sections are reusable templates.

**Comment by brian-mann** [comment]
Closing in favor of https://github.com/cypress-io/cypress-documentation/issues/306

**Comment by fineline** [comment]
Thanks for correcting the doc. Didn't see this mentioned elsewhere - when trying to figure out what the promise yields, the Yields section is where I looked.

My use case is to click through items on a list deleting any previous test entries, which are identifiable by a match on a text pattern. I have now implemented this by getting all items with a cy.get() and then iterating through them with .each() and testing their text with

```js
if ($li.text().match(/MyPattern/)) doStuff()
```

Not quite as concise as a .contains() but does the trick.

**Comment by brian-mann** [comment]
You could probably just do... `cy.get('div:contains(bar)')`

**Comment by 0xIslamTaha** [comment]
I can still see that the docs say `yield firs element` 
![image](https://user-images.githubusercontent.com/17981089/74030777-27dba800-49b0-11ea-88c9-c30997a19f9b.png)

**Comment by obedparla** [comment]
That's correct @0xIslamTaha, it only yields the first element.

**Comment by sijakret** [comment]
> You could probably just do... `cy.get('div:contains(bar)')`

not for me!
```html
<div>a</div>
<div>a</div>
```
```js
cy.get('div') // -> both
cy.get('div:contains(a)') // -> only first
```
wont fix => there is no supported path to do this, right?

**Comment by OlsonDev** [comment]
I can't speak to `cy.get('div:contains(mystr)')` only yielding the first result nowadays, but I suspect that's not true considering this worked for me:

```js
cy.get('[data-test="agreement-status-text"]:contains("Active")').should('have.length', 4)
```

![image](https://github.com/user-attachments/assets/d510a8e0-188c-48b6-b888-9ab1c1bfe45a)
