### ISSUE TITLE
@cypress/react recipes document nextjs example broken link

### ISSUE THREAD

**Issue by itstheandre** [cypress-io/cypress#16054]
In [this file](https://github.com/cypress-io/cypress/blob/develop/npm/react/docs/recipes.md#nextjs) the link for the `nextjs` example is broken.

Is there a way to update it eventually?

I am looking for a working example of component tests and can't find it anywhere.

Cheers

**Comment by lmiller1990** [comment]
Hi!

Good catch. The link is broken. You can find the nextjs example here: https://github.com/cypress-io/cypress/tree/develop/npm/react/examples/nextjs

I have fixed the docs here. https://github.com/cypress-io/cypress/pull/16055

**Comment by itstheandre** [comment]
Hello @lmiller1990 thanks.

The docs, as they are presented dont work.

If I just have the dependencies presented in that example it first complains that you dont have `@cypress/webpack-dev-server` and after that that you dont have `webpack-dev-server`.

Then, you're missing `webpack`. If you install the latest version it breaks because 
```it cant find property 'tap' of undefined ```

Therefore you have to install the version 4 of webpack then it finally works.

**Comment by itstheandre** [comment]
Should I add those dependencies to the `package.json` in that example and send in a PR?

**Comment by lmiller1990** [comment]
Yes please! This is passing on our CI because we probably have a version of webpack installed in the root level `node_modules`.

**Comment by itstheandre** [comment]
Okay, then I will be sending a PR in a couple of minutes! 

It has to be on `version 4` because the version 5 is still not working as seen on #15864.

Eventually when that issue gets closed then the documents will have to also be updated

**Comment by lmiller1990** [comment]
Sure. I will be working on #15864 tomorrow. I should get it fixed this week.

**Comment by itstheandre** [comment]
@lmiller1990 
sent a PR with the fix for this: just tested it from scratch with these dependecies and it should work:
#16057 16057

**Comment by lmiller1990** [comment]
Looks like the examples in `npm/react` intentionally omit specific versions, in favor of using the local version of the `@cypress/webpack-dev-server` etc.

The readme is fixed in #16055. We definitely need more fully completed example projects; I think these should go in their own repo, so people can clone and try them out.

**Comment by jennifer-shehane** [comment]
This has been released.
