### ISSUE TITLE
Aborted requests are not handled by cypress

### ISSUE THREAD

**Issue by Alvai** [cypress-io/cypress#18544]
### Current behavior

Requests cancelled with the AbortController are correctly cancelled in the devtools but cypress still looks for it.

Cypress doesn't notify the tests that the request has been aborted. and when logging the status of the request, it's just "received" with no response.

you can check for the status of the request with cy.get("@alias.all") and verify that the status is not "Complete" but it's a bit hacky

### Desired behavior

After the request is aborted (like chrome shows in the devtools), cypress shouldn't wait for it anymore (so no timeout). And should set the status of the request to "failed"

### Test code to reproduce

https://github.com/Alvai/cypress-abort-controller

### Cypress Version

^8.5.0

### Other

From Flotwig (core team) on Discord:
> this looks like a bug, have you reported it on the github repo? aborted requests should display as completed (and wait as if they are completed)

**Comment by asos-dominicjomaa** [comment]
I am also seeing this, I believe this bug was fixed [here](https://docs.cypress.io/guides/references/changelog#6-7-0) in [this code change](https://github.com/cypress-io/cypress/pull/14885) and I have to assume was subsequently regressed in the next few commits - f6a5d1ea2eaace81ef97fc91f17e9945f5ee85d1, 157e363a2da4d7ae7dcb22be39f1928f57c4382d, ab401ecd359234985b269d8283ff526136eeb4d4. Perhaps @sainthkh / @flotwig / @lmiller1990 could shed some light on these changes?

[This change](f6a5d1ea2eaace81ef97fc91f17e9945f5ee85d1) might be the culprit:
```typescript
const RESPONSE_WAITED_STATES: InterceptionState[] = ['ResponseIntercepted', 'Complete', 'Errored']
const RESPONSE_WAITED_STATES: InterceptionState[] = ['Complete', 'Errored']
```

**Comment by lmiller1990** [comment]
Here is the commit w/ the relevant change: https://github.com/cypress-io/cypress/commit/f6a5d1ea2eaace81ef97fc91f17e9945f5ee85d1#diff-69d255c118af701ac4394ade45cc2ef800e10c879e71cd29cb7b9ae56785b8f3L7

As for checking if a test aborted a request, I'm not sure - I haven't done this before, but I can definitely look into it. I don't see anything in our [docs](https://docs.cypress.io/guides/guides/network-requests#Testing-Strategies) about aborted requests.

Finally, I noticed a UI regression around the aborted request example you posted. It looks like something changed between 8.1.0 and 8.2.0:

## 8.1.0

<img width="838" alt="8 1 0" src="https://user-images.githubusercontent.com/19196536/150069199-c91e3bae-5706-4f5a-a1cd-76367c1308b5.png">


## 8.2.0

<img width="839" alt="8 2 0" src="https://user-images.githubusercontent.com/19196536/150069219-6e01c2a5-d718-4094-8898-18d92ef21276.png">

**Comment by asos-dominicjomaa** [comment]
Frustrating, I have little experience with the Cypress codebase so feel free @lmiller1990, unfortunately we have several tests relying on this faculty.

**Comment by lmiller1990** [comment]
Is the first screenshot what you'd expect to see? I'm trying to make sure I know the desired outcome to I can fix it. The original post makes it seem like there should be some kind of "request cancelled" message in the command log, but I've never seen anything like that.

**Comment by steve-taylor** [comment]
This is still reproducible in 10.10.0 (latest version) using @Alvai's example.

@lmiller1990 the issue in that screenshot is the fetch request between lines 3 and 4. Despite the request being aborted, Cypress is waiting for it to complete.

Here's an updated and annotated screenshot from 10.10.0 using the same reproduction and Chrome dev tools open:
![image](https://user-images.githubusercontent.com/1135589/196086464-326d26d0-ca1c-489f-a735-de98cd50ade6.png)

I'm seeing the same issue with XHR requests, so it's not unique to fetch.

**Comment by lmiller1990** [comment]
Thanks for clarifying this is still an issue. If it's an issue in the latest Cypress, we should definitely prioritize fixing this.

Just to clarify; does this break any tests, or is it just a visual bug (this is my understanding based on what I've seen - which is still a problem, obviously, but not as much as something that changes the pass/fail status of tests).
