### ISSUE TITLE
Cypress dashboard runs duration not ending

### ISSUE THREAD

**Issue by glabrat** [cypress-io/cypress#1891]
### Current behavior:

![image](https://user-images.githubusercontent.com/19995834/41060690-575bd2f6-699e-11e8-9c41-221f7d768fd4.png)

### Desired behavior:

Runs to have some timeout

### Steps to reproduce:

https://github.com/gpincheiraa/bln-frontend-project1/tree/cypress_dashboard
https://travis-ci.org/gpincheiraa/bln-frontend-project1/builds/388817066

When I push to a branch, Travis CI comes to action, even tells the project and run

![image](https://user-images.githubusercontent.com/19995834/41062760-c0cc5ce6-69a4-11e8-8211-92b1db961a66.png)

commands used were: 

```
npm start & (wait-on http://localhost:3000 && cypress run --record --key 27df0bb4-b483-4074-9299-def2f76ff852)
```

**Comment by harvitronix** [comment]
I am seeing this with Circle CI under the follow conditions:

1. Start a build
2. Cancel the build after Cypress tests have started, but before they end.

Cypress Dashboard shows runs running forever (one for > 8 days).

**Comment by brian-mann** [comment]
We'll look into there. There is a worker that runs once every 30 minutes to find timed out builds and marks them as timed out. It's possible a regression occurred in the 3.0 release.

**Comment by brian-mann** [comment]
Fixed.

**Comment by brian-mann** [comment]
Released in [`3.0.2`](https://docs.cypress.io/guides/references/changelog.html#3-0-2).

**Comment by jennifer-shehane** [comment]
@codebender828 This is related to this issue: https://github.com/cypress-io/cypress/issues/2630

**Comment by alexeymolchan** [comment]
still exist in 3.8.1, already more then 90 minutes.

Steps to reproduce: 

1) cypress run --record --key #key

2) kill process (specs started but not finished)

**Comment by jennifer-shehane** [comment]
This issue will be closed to further comment as the exact issue here was resolved and tested. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
