### ISSUE TITLE
"Still waiting to connect to Firefox" issue in Cypress 10.0.2 on Windows

### ISSUE THREAD

**Issue by laerteneto** [cypress-io/cypress#22086]
### Current behavior

The Firefox doesn't load Cypress in both open and headless mode
![image](https://user-images.githubusercontent.com/9399511/171828216-c7ad1cf1-db54-4572-a20f-091f406d3536.png)

### Desired behavior

Cypress must be loaded within the Firefox browser

### Test code to reproduce

In the open mode:
- cypress open
- choose Firefox

Headless:
 cypress run --browser firefox

### Cypress Version

10.0.2

### Other

Windows 10
Firefox 101

**Comment by lmiller1990** [comment]
Thanks for the bug report, and upgrading to Cypress 10 so quickly. I reproduced this - Firefox is timing out for me, too. We are investigating and will publish a patch when we find the cause and solution.

**Comment by stacks13** [comment]
It's timing out on Cypress 8 and 9 as well.

**Comment by lmiller1990** [comment]
Oh, I am also seeing the same problem on 9.7.0 as pointed out by @stacks13. I guess this is not a Cypress 10 specific regression? Needs more investigation.

**Comment by roshan04** [comment]
@lmiller1990 I am facing the same issue with firefox 101 on cypress 9.5.1. The browser is getting launched but still showing the error: **Waiting to connect to firefox**. Attaching the screenshots. Can you help here.
<img width="1234" alt="Screenshot 2022-06-03 at 4 06 40 PM" src="https://user-images.githubusercontent.com/47280057/172102173-8720bfdc-3869-41a9-8f95-1e666e520456.png">
<img width="1243" alt="Screenshot 2022-06-03 at 4 07 16 PM" src="https://user-images.githubusercontent.com/47280057/172102295-df90aba4-ce7d-42ff-aeb8-7a96a09bb8a8.png">

**Comment by lmiller1990** [comment]
Thanks for sharing - I reproduced and can clarify it's windows + Firefox only.

I am unsure why this is occurring, and if it's two different, unrelated regressions or the same. We will investigate.

**Comment by fanksin** [comment]
Check if you get any error on 127.0.0.1

If you use any kind of local development environment software like xampp or mamp, etc, be sure they are properly closed. If not, start your local server and stop it after everything works properly. 

Besides you can run the command **pnpx kill port 51827** which kills the port I came across that was being used by cypress to run Firefox on 127.0.0.1:51827

**Comment by laerteneto** [comment]
> It's timing out on Cypress 8 and 9 as well.

I was able to reproduce the same issue in Cypress 9.7.0/Windows10/Firefox 101.

**Comment by tomrobst** [comment]
Hi,

Just adding some additional info as I'm having the same issue on Cypress v10.0.3 and Firefox v101.

When starting e2e tests on Firefox, the browser opens but does not start cypress and the console outputs: "Still waiting to connect to Firefox, retrying in 1 second..." etc

I have run Cypress with debugging enabled and it seems there is an issue finding the browser target:

2022-06-07T14:48:40.987Z cypress:server:browsers:browser-cri-client Attaching to target url about:blank
Still waiting to connect to Firefox, retrying in 1 second (attempt 25/62)
2022-06-07T14:48:40.988Z cypress:server:browsers:browser-cri-client error finding browser target, maybe retrying { delay: 1000, err: Error: Could not find url target in browser about:blank. Targets were [] at C:\Users\tomro\AppData\Local\Cypress\Cache\10.0.3\Cypress\resources\app\packages\server\lib\browsers\browser-cri-client.js:90:27 at processTicksAndRejections (node:internal/process/task_queues:96:5) at retry (C:\Users\tomro\AppData\Local\Cypress\Cache\10.0.3\Cypress\resources\app\packages\server\lib\browsers\browser-cri-client.js:39:20) at setupRemote (C:\Users\tomro\AppData\Local\Cypress\Cache\10.0.3\Cypress\resources\app\packages\server\lib\browsers\firefox-util.js:109:27) }

Manually going to the baseURL in the opened browser window (in my case http://192.168.1.107:8081/__/#/specs) does open the cypress specs in Firefox and testing seems to work from this point, however the cypress command line log still fails to connect.

WIndows 11 Pro 10.0.22621
Firefox 101.0 (64-bit)
I'm running Cypress under WSL2. 

Thanks very much!
Tom

**Comment by JohnLukeBentley** [comment]
I get this issue too, as described at https://github.com/cypress-io/cypress/discussions/22117.

**Comment by lmiller1990** [comment]
Thanks all - in this area there is another PR https://github.com/cypress-io/cypress/pull/22168. I don't think it's aiming to address this problem, but it might help. At the very least, referencing here so when someone picks this up, they have something to go off.

**Comment by JohnLukeBentley** [comment]
Given @stacks13's
> It's timing out on Cypress 8 and 9 as well.

... the obvious implication seems to be that the problem Cypress/Windows/Firefox interaction arises not from anything introduced in Cypress 10; but from something introduced in Firefox from v101 (or introduced in Firefox v101 on Windows) ... that Cypress was never coded to accommodate.

**Comment by wball-pcty** [comment]
I am running into this on windows 10, with cypress 9.7.0, and firefox 101. Cypress successfully launches firefox, but fails to connect. The interesting thing that I found though is, if you open a new firefox window from the instance of firefox that cypress launches, cypress connects.

**Comment by wball-pcty** [comment]
If I launch firefox with the "-browser" option, it will open two windows automatically and connect.

**Comment by tbiethman** [comment]
Thank you all for your patience while we investigate this issue. I can corroborate the many comments here and have repro'd the issue in my windows environment.

I am currently digging through the CDP logs and FF101 changes to see where we're no longer compatible. The `target-created` event is either not getting emitted or not being listened to for the initial window, so it never gets detected and we never connect. @wball-pcty like you mentioned, opening a new window manually causes the event to be emitted and allows the target to be detected on subsequent connection attempts. 
 
We also succeed if we launch Firefox in troubleshooting mode with the `-safe-mode` option. I'm currently comparing logs to see how this might be impacting the launch.

**Comment by awaiskhalil** [comment]
Facing the same issue in latest cypress release
**cypress: 10.1.0
Firefox: 101 (64-bit)**

Cypress failed to make a connection to Firefox.

This usually indicates there was a problem opening the Firefox browser.

Error: Could not find url target in browser about:blank. Targets were []

![Snag_23668927](https://user-images.githubusercontent.com/17334723/173801250-d31c4dc4-2ca4-489c-81d2-cc7df1141573.png)

**Comment by tomrobst** [comment]
> Thank you all for your patience while we investigate this issue. I can corroborate the many comments here and have repro'd the issue in my windows environment.
> 
> I am currently digging through the CDP logs and FF101 changes to see where we're no longer compatible. The `target-created` event is either not getting emitted or not being listened to for the initial window, so it never gets detected and we never connect. @wball-pcty like you mentioned, opening a new window manually causes the event to be emitted and allows the target to be detected on subsequent connection attempts.
> 
> We also succeed if we launch Firefox in troubleshooting mode with the `-safe-mode` option. I'm currently comparing logs to see how this might be impacting the launch.

Thanks for the update on this and appreciate the work investigating the issue.

The workaround by opening a new window (Ctrl+n) when Firefox starts, allowing Cypress to register the new target, works well for me in the meantime.

**Comment by laerteneto** [comment]
I found a workaround for the open mode. If you copy your URL form other Chrome based browser when it opens (for example yourURL/__/#/specs) and paste it in Firefox while it is trying to connect, it will connect. Unfortunately, this workaround is restricted to the open mode.

**Comment by lmiller1990** [comment]
Oh nice, I guess FF fixed something! Good to know. Hopefully some other people commenting can try FF 104 and see if it's resolved.

**Comment by pedy711** [comment]
Firefox nightly works for me too.

**Comment by lmiller1990** [comment]
@tbiethman not sure if you are actively working on this (assigned to you) but maybe we can close this as resolved - FF seems to have fixed the issue?

**Comment by tbiethman** [comment]
@lmiller1990 Yep, a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1774476) was identified and a fix has made it into beta/nightly channels. I wanted to keep this open until the fix made it into a stable 103 release, looks like it'll land July 26th.

**Comment by JohnLukeBentley** [comment]
(Noting I'm just a punter, not on the cypress team) @lmiller1990 as a general matter I would suggest it best to keep issues open until they are resolved in the stable versions of the relevant software, as @tbiethman indicates. For two reasons: 

1. There's the small risk that between a beta (or alpha, or nightly) version and a stable release the apparent resolution might regress; and 
2. Keeping the issue open advertises that it remains a problem for those users who are using stable versions that have not yet had the fix folded into them.

As a matter of being on the dev team hunting for issues to manage and work on you could always add a label (and filter on that label). Wouldn't one of the currently applied labels, "stage: waiting", be fulfilling this purpose? If not you could add something like "stage: waiting-on-external-fix", "stage: waiting-on-external-stable-release", or something else that makes sense in your overall workflow (which I'm not across).

**Comment by iomedico-beyer** [comment]
I am seeing this also on Gitlab CI in a cypress/browsers:node16.14.2-slim-chrome100-ff99-edge Docker container. So it's also happening on Linux.

**Comment by tbiethman** [comment]
Hey all 👋 , Firefox 103.0 released today and I'm happy to say I can no longer reproduce the original issue with that version. Please update and report back if you're still running into issues.

@iomedico-beyer this ticket was originally tracking a pretty targeted failure with FF 101/102 on windows. We've had a couple reports of other connection failures, like you've linked, but we've been thus far unable to repro those in-house. If you log a new issue with more details about your environment and logs, we can investigate your issue further.

**Comment by rajendran-k** [comment]
Updating to Firefox 103.0 is fixing the issue in Windows.

**Comment by kenwiro** [comment]
Updating to Firefox 103.0 is reproducing this issue on MacOs 12.2.1

**Comment by laerteneto** [comment]
> Updating to Firefox 103.0 is fixing the issue in Windows.

Yes, the same in here. It looks like everything is back to normal.
Running ok on Firefox 103 + Windows 10 + Cypress 10.3.1

**Comment by tbiethman** [comment]
@kenwiro I'm able to connect to Firefox 103 on macOS with Cypress. Might be something else going on? Feel free to create a new issue with your Cypress debug logs and we can take a look.

**Comment by tbiethman** [comment]
Closing this as complete now that Firefox 103.0 is released and the original issue is resolved.

**Comment by tobysmith568** [comment]
FYI: Firefox 103 has just made it into the images for the GitHub Actions `windows-latest` agents 🎉

https://github.com/actions/virtual-environments/pull/5993

**Comment by ChristianMLux** [comment]
DevOps CI, FF 103, Cypress 9.5.0

> Closing this as complete now that Firefox 103.0 is released and the original issue is resolved.

https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md

Can anyone give me a tip on what else I can do here? 

According to the readme of the Unbuntu image, the Firefox version has already been updated to V103. Unfortunately, I'm still facing the bug mentioned above

![image](https://user-images.githubusercontent.com/85493442/183641313-c2fcc001-7675-4af2-9189-01a9e750923e.png)

**Comment by 25natan** [comment]
I'm having same problem on cypress 9.6.0
when running with `open` and select firefox 104 I get `404 page not found` and when running with `run`  I keeps logging 
`Still waiting to connect to Firefox, retrying in 1 second`

**Comment by audriusnavickasDB** [comment]
This issue is still relevant and not completely fixed. 

- It is still reproducible on Cypress v10.8.0, Firefox v105.0.1 on Windows 10/11, macOS and Linux. 
- It does not matter if you run it with cypress run or open command. 
- It works perfectly fine with other browsers. 
- Firefox Nightly v107 has the same issue as the simple Firefox browser.

`cypress:network:connect retries exhausted, bubbling up error { iteration: 63, err: Error: connect ECONNREFUSED 127.0.0.1:63412     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 63412 } } +1s
  cypress:server:browsers:browser-cri-client failed to connect to CDP { connectOpts: { host: '127.0.0.1', port: 63412, getDelayMsForRetry: [Function: getDelayMsForRetry] }, err: OperationalError: connect ECONNREFUSED 127.0.0.1:63412     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { cause: Error: connect ECONNREFUSED 127.0.0.1:63412     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 63412 }, isOperational: true, errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 63412 } } +3m
`

Tried various suggested solutions like:

- Different node version
- Change localhost to 127.0.0.1 or just use something like https://google.com
- Disable gpu before browser launch (launchOptions.args.push('--disable-gpu'))
- And some more can't remember all of them

However the only solution that worked for me was to downgrade Cypress version. The versions which are working completely fine with Firefox v105 and not throwing this issue are:
- 9.5.4
- 9.6.0
- 9.7.0

Since Cypress v10.x.x it is not working anymore. It cannot initialise properly the first tab of Firefox browser with necessary address and everything gets stuck. It would be really a great help if someone could take a look once again to this specific issue.

Steps to reproduce it are quite simple:
- Install cypress version 9.5.4 on empty directory and just run cypress open, it will add some mock test cases
- Ensure you have latest Firefox browser version
- Test it if any test suite runs on FF - it should
- Upgrade Cypress version to v10
- Run cypress open, do the migrations and stuff, pick any test suite on FF - should not be able to run it and will throw errors in terminal: Still waiting to connect to Firefox, retrying in 1 second

**Comment by luke-sensei** [comment]
I confirm the issue is NOT fixed on windows 11 + cypress 10.9 + firefox 105

**Comment by ivanpepelko** [comment]
Issue also persists with:
- Ubuntu 20.04.5 LTS + Cypress: 9.6.0 + Browser: Firefox 104 (headless) +Node Version: v16.17.0 (plain github actions runner)
- Arch (kernel 5.19.11-arch1-1) + Cypress: 9.6.0 + Browser: Firefox 105 (headless) +Node Version: v16.17.1

**Comment by oguzhantx** [comment]
This issue still persists with 
MAC OS, Cypress 10.3, Firefox 103,100,105

**Comment by DRWAUN** [comment]
This issue is not fixed on Windows 10 21H2 with Cypress 10.7.0 and Firefox v105/Firefox Developer Edition v106

**Comment by German152015** [comment]
El problema persiste Cypress 10.8 y Firefox v.105, alguna solución?

**Comment by abmaelrodrigo** [comment]
Issue still not fixed on macOS Monterey, Cypress 10.7.0, Firefox v105.0.1

**Comment by spiltcoffee** [comment]
I believe all of the new conenction problems since this issue was closed are related to #23897.

Side note, ~while that issue is closed (for some reason?)~ edit: issue reopened, Mozilla is still investigating the issue, so keep an eye on the related issue in the Firefox bug tracker.

**Comment by 403-html** [comment]
^also note: reversing to v104 Firefox seems to "fix" the problem

**Comment by nikolas** [comment]
Looks like this is an issue with Firefox 105 in our setup as well. Using Firefox 102.3.0esr instead, the cypress tests run fine. https://github.com/ccnmtl/mediathread/pull/4658

**Comment by Dan5123** [comment]
Hello guys,
I have similar issue with Chrome, it has failed to launch the test runner.


![3](https://user-images.githubusercontent.com/106591615/194878433-9731ce1c-6729-44d1-923b-589b0a4852b3.png)
![1](https://user-images.githubusercontent.com/106591615/194878449-2b9a3864-6fc8-4b88-bc83-17be1c228eeb.png)
![2](https://user-images.githubusercontent.com/106591615/194878460-0bf45764-6004-404c-b298-b65a6e4b3da8.png)

**Comment by brentsharon** [comment]
Yes this is an issue and is occurring for me using Cypress 10.9.0 FFv105 on a mac.  I was also getting this issue on 10.8.0 before the update to 10.9.0.   This is an issue with both the runner and headless.

**Comment by Dan5123** [comment]
is there any one who can help please 

![3](https://user-images.githubusercontent.com/106591615/195041836-72b27f73-d69b-4425-b54d-659bf8bd550a.png)

**Comment by spiltcoffee** [comment]
@Dan-appreciategroup you're probably better off making a new issue for your problem as this issue is specifically a Firefox issue - and closed, might I add! You're very unlikely to get any support in this issue.

**Comment by Dan5123** [comment]
@spiltcoffee  thanks

**Comment by brentsharon** [comment]
@Dan-appreciategroup @spiltcoffee I did make a new issue for this yesterday and got an email that a fix is out in the new release today 10.10.0

**Comment by spiltcoffee** [comment]
@brentsharon the main issue you'll be looking for is #23897, and the fix is in #24155, though I haven't checked if the changes in that PR have made it into a release yet.

**Comment by brentsharon** [comment]
@spiltcoffee thanks

**Comment by Dan5123** [comment]
@brentsharon I have opened a new issue and it has been assigned to someone from Cypress team #24199

**Comment by brentsharon** [comment]
@Dan5123 Awesome thanks!

**Comment by hodbby** [comment]
Any update / fix here?
Firefox v 129.0 (64b)
Cypress 13.6.3
Ubuntu 22

Still waiting to connect to Firefox, retrying in 1 second

**Comment by lazovskih** [comment]
> Any update / fix here? Firefox v 129.0 (64b) Cypress 13.6.3 Ubuntu 22
> 
> Still waiting to connect to Firefox, retrying in 1 second

I had the same issue. Try this:
Uninstall firefox -> re-install firefox.
Uninstall Cypress -> re-install Cypress (in my case I installed the latest - my was 13.11.00 I upgraded to 13.13.2).
Worked for me!

**Comment by MuzamilHassan1** [comment]
Hey, was anyone able to solve this issue?

**Comment by HappyMan0001** [comment]
I'm seeing the same issue on Cypress 13.1.0; Firefox is up to date. it is just not working on Firefox.
![firefoxFailure](https://github.com/user-attachments/assets/2b92714f-db63-4d6b-b36c-cc3c3fa962c0)
![firefoxFailureAbout](https://github.com/user-attachments/assets/65cf10e6-85f7-422a-99da-90530b42ecc5)

**Comment by jennifer-shehane** [comment]
@HappyMan0001 Please open a new issue with reproducible example + steps. I'm able to open and connect to firefox 131 in Cypress.

**Comment by yhaiovyi-tripactions** [comment]
Both Chrome and Firefox stopped working. First Chrome started failing with the empty response error, and now Firefox opens but does nothing and Cypress fails to connect to it.

**Comment by svetlana-napris-elucid** [comment]
Same issue for me. Firefox 135 and Cypress 13.7.0

![Image](https://github.com/user-attachments/assets/a64ff75c-9d8e-4e03-9b03-a402a20e3117)

Did someone have a chance to open a new issue?
