### ISSUE TITLE
Cypress 10.8.0: Video Randomly Freezing When Recording Tests

### ISSUE THREAD

**Issue by vikingair** [cypress-io/cypress#23824]
### Current behavior

After updating from Cypress@10.7.0 to Cypress@10.8.0 the test executions randomly freeze. Looking at the videos, you can see that the application crashed as no error is reported but the test runner exits with non zero exit code.

The following is displayed without any movements (not even spinner continue to rotate in the panel) for the last 5 seconds of the video.

<img width="501" alt="Bildschirmfoto 2022-09-14 um 11 04 37" src="https://user-images.githubusercontent.com/17571883/190111348-259c688d-c9d2-40cb-af5f-be79ff639309.png">

### Desired behavior

Cypress@10.7.0 worked without any issues. Since your have worked on memory improvements with release 10.8.0 it is very likely that this issue is related to these changes.

### Test code to reproduce

// the code is subject to privacy and is not required here as the error occurs randomly on all kind of tests

### Cypress Version

10.8.0

### Node version

v16.14.0

### Operating System

Linux Ubuntu Latest GitHub Workflow

**Comment by emilyrohrbough** [comment]
@fdc-viktor-luft Can you give more details on how you are running Cypress, the configuration, and the general setup of your spec that is causing this error? I haven't observed the behavior in our test suite. Doesn't mean this isn't a problem for you but we need some guidance on how to repo this.

**Comment by vikingair** [comment]
@emilyrohrbough Sure, sorry for providing so little details. Thanks for taking care 👍 

Running command: `pnpm test`
With script in package.json: `"test": "cypress run --e2e"`

Cypress-Config:

```ts
import { defineConfig } from 'cypress';
import { readFileSync } from 'fs';
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import { lighthouse, pa11y, prepareAudit } from 'cypress-audit';

const conf = JSON.parse(readFileSync(process.env.CONF, 'utf-8'));

export default defineConfig({
    e2e: {
        setupNodeEvents(on, _config) {
            on('before:browser:launch', (_browser, launchOptions: any) => {
                prepareAudit(launchOptions);
            });

            on('task', {
                lighthouse: lighthouse(), // calling the function is important
                pa11y: pa11y(), // calling the function is important
            });
        },
        specPattern: 'src/**/*.cy.{js,jsx,ts,tsx}',
        baseUrl: conf.domain,
        env: {
            CONFIG: JSON.stringify(conf),
        },
        viewportWidth: 1200,
        viewportHeight: 800,
    },
});
```

And `cypress-audit` with version: 1.1.0

Test example:

```ts
const CONFIG = JSON.parse(Cypress.env('CONFIG'));

describe('Employee Login', () => {
    it('log in as employee and logout again', () => {
        cy.visit('/');

       cy.get('input#email').type(CONFIG.credentials[user].email);
       // secret should not be logged
       cy.get('input#password').type(CONFIG.credentials[user].password, { log: false });
       cy.get('button[type="submit"]').click();
       // wait for the navigation sidebar to appear
       cy.get('.navigation-sidebar');

      cy.get('[data-test-id="logout"]').click();
   });
});
```

**Comment by emilyrohrbough** [comment]
@fdc-viktor-luft  Can you share a bit more? What error are you seeing? And what is the behavior of the the submit handler / xhr that is being triggered? Is this a redirect that sends cookies? Is this an update in the application under tests to rerender when authenticated?

Is this test the only place you are experiencing this hang? We also fixed some same-site cookie related issues in 10.8.0 so want to ensure this might not be related to those changes.

**Comment by vikingair** [comment]
The submit handler performs:
- Loading some ReCaptcha script
- Triggering a Fetch-Request to perform the login
- This request sets some cookie value
- Finally a page reload

The error looks like a "normal" timeout error:

```
AssertionError: Timed out retrying after 4000ms: Expected to find element: `.navigation-sidebar`, but never found it.
```

But I've also seen other errors that were trying to wait for elements that are not even on the screen yet, when the Cypress Video freezes. So it must be that Cypress still continues execution, but the Recording just stopped.

The other errors are not happening on authentication. Therefor I don't think that setting the cookie or any other authentication related things are causing the issue.

And, I've also experienced that the above tests work in 75% of cases currently.

And, I've checked now the produced videos of succeeding tests. I've found that the videos are just freezing. Cypress seems to continue its execution.

**Comment by emilyrohrbough** [comment]
@fdc-viktor-luft Thanks for digging in a bit more. This is super helpful in understanding what might be happening.

Based on your findings, it seems this issue can accurately be summarized as "Cypress video recording randomly freezes while tests continue"? or am I mis-understanding the issue you are trying to describe?

**Comment by vikingair** [comment]
Yes. It seems so. I mean some of them are still failing for unknown reason, but I couldn't find the reason in the Videos 🙃 

Would you suggest to raise a separate issue for that, if it keeps randomly failing?

Also, we have experienced our tests to run now almost twice as slow.

A test run with only success with version 10.7.0: ~ 6 min
A test run with only success with version 10.8.0: ~ 10,5 min

I would expected that Cypress would become faster with the recent update 😞 

**Update**: Last test run with version 10.8.0 took 15,25 min and one test was failing for random reason again. So we need to downgrade now temporarily.

**Update 2**: After rolling back to 10.7.0 the tests executed again in 4,75 min with success.

**Comment by emilyrohrbough** [comment]
@fdc-viktor-luft Sounds good. Can you confirm the browser(s) you are having this issue with?

Also, if you aren't able to identify the issue from the videos, I would try running the spec in question with the flags `--headed --no-exit` so you can watch it run and then debug when it finishes. https://docs.cypress.io/guides/guides/command-line#cypress-run-no-exit

**Comment by vikingair** [comment]
Running in the CI. Cypress prints this:

```
  │ Cypress:        10.8.0                                                                         │
  │ Browser:        Electron 102 (headless)                                                        │
  │ Node Version:   v16.14.2 (/opt/hostedtoolcache/node/16.14.2/x64/bin/node)                      │
```

**Comment by Narretz** [comment]
Looks like the only commit that touched video was a refactor, although a pretty big one: https://github.com/cypress-io/cypress/commit/bcd7548d74fdb5dab4790f10f158bb4f3e9387bc

**Comment by lediur** [comment]
I'm running into a similar issue on Cypress 10.9 in GitHub Actions (using standard-spec GitHub-hosted runners). In my case, the video seems to freeze at the beginning while tests are loading. After that, they update very sporadically (up to a few minutes between frames) throughout the playtime.

This seems to only occur in CI. Video seems to record and playback as expected when I run tests locally. I wonder if this is caused by low memory.

edit: I just tried downgrading to 10.7.0 and running in GitHub, and both test runs I've tried seem to record just fine with no issues.

**Comment by cgraham-rs** [comment]
Have been experiencing this issue for a while and have been ignoring it. But lately have been chasing flake and test failures and the fact the video freezes for long periods of time makes debugging impossible.

* Github Actions
* Cypress 10.10.0 (and at least some versions prior)
* Cypress Dashboard
* Chrome videos (since Firefox videos still do not work at all for the past year)

[The Cypress Dashboard example I was looking at today](https://dashboard.cypress.io/projects/dhybrn/runs/1570/test-results/89e3f076-f072-49c4-b5a0-1ffab2bac6a7/video) the video worked from 00:00 - 00:15, froze until 00:43 where it updated what looks like a single video frame and immediately froze again until 01:28, updated what looks like a single video frame and immediately froze again until 02:40. Essentially the video is completely useless.

As another user pointed out the Cypress Command Log isn't even spinning/moving.

I've completely disabled video compression in `cypress.config.ts` hoping that was the issue, which it is not. 
```
videoCompression: false
```

**Comment by cgraham-rs** [comment]
Observed that the video dimensions and meta data are identical from cypress run locally and in CI with the exception that the video available via Dashboard is a fraction of the file size even though the video is 2x as long in CI.

Local: 
* video length: 2:58
* file size: 59.6MB

CI:
* video length: 7:49
* file size: 22.5MB

**Comment by kasper573** [comment]
I have also experienced this bug. Here's some findings from my debugging:

Changing from 10.7.0 to 11.2.0 introduced this issue for me. 10.7.0 was fast, 11.2.0 became slow, and reverting fixed the issue consistently. I was using electron in both versions.

Side note: Switching to using headless chrome in CI for 11.2.0 seemed to also fix the issue, so I'm thinking this could be related to electron in 11.2.0. But that's just me guessing.

**Comment by vikingair** [comment]
This ticket is related to this one: https://github.com/cypress-io/cypress/issues/23830

In here we have already feedback from several engineers that a bigger refactoring of the video recording has caused this issue. Turning off the video recording will bring back old speed.

This was introduced in version 10.8.0 and from what I've heard, it wasn't fixed yet. Don't know why this issue still has not highest priority 🙃

**Comment by jennifer-shehane** [comment]
Is this still an issue? It's been a while since this was reported and I know we fixed an issue with videos in Electron here: https://github.com/cypress-io/cypress/pull/25189

**Comment by cgraham-rs** [comment]
None of my teams currently record video with Cypress tests. We do however use Replay and have zero issues, and it's a vastly superior debugging tool compared to basic videos. 

Hopefully, someone still recording video can comment as to the current performance.

**Comment by vikingair** [comment]
We stopped recording videos in the CI as well as it was consuming too much resources and slowed down all tests significantly. Hence, I have nothing to report. Sorry.

**Comment by jennifer-shehane** [comment]
We'll close this issue until new evidence suggests this is still occurring. I would also suggest using Test Replay instead of video. It is a lot better at debugging even our own tests.
