### ISSUE TITLE
Fix electron deprecated new-window event

### ISSUE THREAD

**Issue by KirIgor** [cypress-io/cypress#24775]
### Current behavior

```
Trace: The new-window event is deprecated and will be removed. Please use contents.setWindowOpenHandler() instead.
    at Object.log (node:electron/js2c/browser_init:225:603)
    at emitDeprecatedNewWindowEvent (node:electron/js2c/browser_init:185:1303)
    at openGuestWindow (node:electron/js2c/browser_init:185:1685)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:165:14118)
    at EventEmitter.emit (node:events:527:28)
Trace: The new-window event is deprecated and will be removed. Please use contents.setWindowOpenHandler() instead.
    at Object.log (node:electron/js2c/browser_init:225:603)
    at emitDeprecatedNewWindowEvent (node:electron/js2c/browser_init:185:1303)
    at openGuestWindow (node:electron/js2c/browser_init:185:1685)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:165:14118)
    at EventEmitter.emit (node:events:527:28)
```

### Desired behavior

No error.

### Test code to reproduce

In specs:

```js
const openedWindows = []

const options = {
  onBeforeLoad: win => cy.stub(win, "open", (...args) => {
    const newWindow = window.open(...args)
    openedWindows.push(newWindow)
    return newWindow
  }),
}

cy.visit("/", options)
```

In code:

```js
window.open("https://example.com/", "_self")
```

### Cypress Version

11.1.0

### Node version

16.14.0

### Operating System

macOS 12.0

### Other

https://www.electronjs.org/docs/latest/breaking-changes#deprecated-webcontents-new-window-event

**Comment by alexsch01** [comment]
Hope this gets fixed soon

**Comment by rockindahizzy** [comment]
Hi @KirIgor, Thanks for reporting this! I will route this over to the team responsible for this part of the application!

**Comment by karlkovaciny** [comment]
This issue makes my entire test run crash with a SIGABRT, which my CI server doesn't print to the log. If that's common, then this would be a good one to prioritize, since it's more trouble to solve than just following the link in the log. It also doesn't reproduce locally until you realize that you have to use Electron instead of Chrome.

**Comment by cposada23** [comment]
This is still happening on cypress 12.2.0

**Comment by prabin-khadka** [comment]
This issue is happening on cypress 12.2.0 for me as well.

**Comment by alexsch01** [comment]
Can we have an update on the status of this issue?

**Comment by pallavL01** [comment]
Is there any update on the issue? Or is there a way to mitigate the issue?

**Comment by camiloesub** [comment]
This is a really annoying issue, we want to update the cypress version but we can not do it because we keep getting The new-window event is deprecated and will be removed. Please use contents.setWindowOpenHandler() instead

Tried using cypress latest 12.3.0 by the way

**Comment by stevenmcsorley** [comment]
Im having to add this to make other tests continue running even though this test is passing in the cypress UI and Im not testing if the new window opens Im testing Ga events fired on click

```
When(`I click on the {string}`, (link: any) => {
  cy.window().then((win: any) => {
    // And I listen to GTM's dataLayer.push method
    let dlp;
    if(!dlp){
       dlp = cy.spy(win.dataLayer, "push").as("dlp");
    }
    cy.wait(2000);

    // When I click on the link ( temp prevent new tab opening as we are testing ga events not what is in the new tab)
    cy.get(link).should('exist').invoke('removeAttr', 'target').click({ multiple: true });
  });
});
```

**Comment by camiloesub** [comment]
Tried Cypress 12.4.0....... Still happening, is cypress never going to do anything about this ?

**Comment by alexsch01** [comment]
@nagash77 This is affecting a lot of users. Should cypress roll back its version of electron?

**Comment by natalyayyad** [comment]
I'm facing this issue too. I'm on 12.3.0. 
in cypress UI I face just hanging In headless mode i got this message: 

```
Trace: The new-window event is deprecated and will be removed. Please use contents.setWindowOpenHandler() instead.
    at Object.log (node:electron/js2c/browser_init:225:603)
    at emitDeprecatedNewWindowEvent (node:electron/js2c/browser_init:185:1303)
    at openGuestWindow (node:electron/js2c/browser_init:185:1685)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:165:13149)
    at EventEmitter.emit (node:events:527:28)
```

**Comment by jonakote** [comment]
@natalyayyad  
I got my resolved by specifying a different browser available on the system.
I use the windows OS so I specified edge

`npx cypress run --browser edge`

**Comment by bencelang** [comment]
In our case using `11.2.0`, this is followed by a V8 crash:
```
Trace: The new-window event is deprecated and will be removed. Please use contents.setWindowOpenHandler() instead.
    at Object.log (node:electron/js2c/browser_init:225:603)
    at emitDeprecatedNewWindowEvent (node:electron/js2c/browser_init:185:1303)
    at openGuestWindow (node:electron/js2c/browser_init:185:1685)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:165:14118)
    at EventEmitter.emit (node:events:527:28)
Trace: The new-window event is deprecated and will be removed. Please use contents.setWindowOpenHandler() instead.
    at Object.log (node:electron/js2c/browser_init:225:603)
    at emitDeprecatedNewWindowEvent (node:electron/js2c/browser_init:185:1303)
    at openGuestWindow (node:electron/js2c/browser_init:185:1685)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:165:14118)
    at EventEmitter.emit (node:events:527:28)
#
# Fatal error in HandleScope::HandleScope
# Entering the V8 API without proper locking in place
#
The Test Runner unexpectedly exited via a exit event with signal SIGILL
Please search Cypress documentation for possible solutions:
https://on.cypress.io/
Check if there is a GitHub issue describing this crash:
https://github.com/cypress-io/cypress/issues
Consider opening a new issue.
----------
Platform: linux-x64 (Ubuntu - 16.04)
Cypress Version: 11.2.0
```

**Comment by vieira-avmb** [comment]
Still an issue on `12.7.0`.

```
Trace: The new-window event is deprecated and will be removed. Please use contents.setWindowOpenHandler() instead.
    at Object.log (node:electron/js2c/browser_init:225:603)
    at emitDeprecatedNewWindowEvent (node:electron/js2c/browser_init:185:1303)
    at openGuestWindow (node:electron/js2c/browser_init:185:1685)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:165:14118)
    at EventEmitter.emit (node:events:527:28)
```

**Comment by George3d6** [comment]
Are there any update on what is causing this and what are some workarounds?

It seems to popup on very basic "click on a href" style scenarios which sort-of remove 101 functionality I'd expect from cypress

**Comment by gonzalo-diamend** [comment]
This is still happening in Cypress 12.9.0
```
Trace: The new-window event is deprecated and will be removed. Please use contents.setWindowOpenHandler() instead.
    at Object.log (node:electron/js2c/browser_init:225:603)
    at emitDeprecatedNewWindowEvent (node:electron/js2c/browser_init:185:1303)
    at openGuestWindow (node:electron/js2c/browser_init:185:1685)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:165:14118)
    at EventEmitter.emit (node:events:527:28)
```

![image](https://user-images.githubusercontent.com/25432206/228787526-d912f530-a340-4296-9354-5b8b1388a71a.png)

**Comment by andrii-lundiak** [comment]
I also have this issue for Cypress `v12.9.0` (still happening for `v12.11.0` for me too) and if I understand correctly what it's really Electron issue. Coz I see it on CI so far (where my tests executed by default towards Electron browser).

![image](https://user-images.githubusercontent.com/85486996/229471119-dfa6e267-a037-4975-b46e-8c74c2122035.png)

Good or bad but my main application uses `window.open()` for the business feature. And I can't change it now.
But my e2e test with Cypress tries to verify if it it only open window.

Or when I execute via GUI by selecting Electron:
![image](https://user-images.githubusercontent.com/85486996/229474586-a3c7d029-56ed-4d18-b94f-65ffd5435e0c.png)


Here is part of my Cypress `it()`:

```
cy.window().then((win) => {
      // 'spy' vs 'stub' lets the new tab still open if you are visually watching it
      // plus 'stub' is partially deprecated.
      cy.spy(win, 'open').as('windowOpen');
      // '@windowOpen' is $Chainer and contains specWindow as instance of Window.
});

....

cy.get('mat-dialog-actions').contains(openInNewWindow).click().then(() => {
        const url = '/my-custom-new-window';
        const targetWindowName = 'TBD';
        cy.get('@windowOpen').should('be.calledWith', url, targetWindowName);
        // We can't close that new window because we spy only its method .open()
});

```

So I somehow can agree, that in XXI cent. when SPA still is a standard, we have to AVOID `window.open()` but for me it was such business request. And I am anyway surprised, that Electron starts doing breaking changes. I mean I can't manage/influence on that part of V8 if I execute Cypress test. right? Any better Cypress ideas how to achieve similar result without that warning? https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/stubbing-spying__window

**Comment by omartaghlabi** [comment]
I'm running into this issue using Cypress version 12.8.1. 
In my case, this trace is returned when clicking a button that opens a new tab:
```
Trace: The new-window event is deprecated and will be removed. Please use contents.setWindowOpenHandler() instead.
    at Object.log (node:electron/js2c/browser_init:225:603)
    at emitDeprecatedNewWindowEvent (node:electron/js2c/browser_init:185:1303)
    at openGuestWindow (node:electron/js2c/browser_init:185:1685)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:165:14118)
    at EventEmitter.emit (node:events:527:28)
  ```
 Once this happens, the next test returns the following and then the entire Cypress run stops:
 
 ```
 ERR_FAILED (-2) loading 'about:blank'
Error: ERR_FAILED (-2) loading 'about:blank'
    at rejectAndCleanup (node:electron/js2c/browser_init:165:7500)
    at EventEmitter.stopLoadingListener (node:electron/js2c/browser_init:165:7875)
    at EventEmitter.emit (node:events:527:28)
 ELIFECYCLE  Command failed with exit code 1.
 ```
 
 I tried running my tests in Chrome and Edge but they take way longer than when ran against Electron. Is there a workaround that doesn't include running the tests in another browser?

**Comment by ganeshthreado** [comment]
cypress - `12.11.0`

Still happening...
```
Trace: The new-window event is deprecated and will be removed. Please use contents.setWindowOpenHandler() instead.
    at Object.log (node:electron/js2c/browser_init:225:603)
    at emitDeprecatedNewWindowEvent (node:electron/js2c/browser_init:185:1303)
    at openGuestWindow (node:electron/js2c/browser_init:185:1685)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:165:14118)
    at EventEmitter.emit (node:events:527:28)
```

**Comment by mejo-** [comment]
I ran into the same bug now with Cypress 12.11.0 and 12.12.0.

**Comment by gino8080** [comment]
is there any workaround?

**Comment by nahuelavila** [comment]
Still occurring in Cypress 12.13.0. I'm running my tests in Edge temporarily until a fix is released.

**Comment by mquerquez** [comment]
> is there any workaround?

For the meantime, what worked for me is to specify a different browser (using chrome for the moment).

**Comment by kchuist** [comment]
same, encounter it in v12.14.0
Trace: The new-window event is deprecated and will be removed. Please use contents.setWindowOpenHandler() instead.
    at Object.log (node:electron/js2c/browser_init:225:603)
    at emitDeprecatedNewWindowEvent (node:electron/js2c/browser_init:185:1303)
    at openGuestWindow (node:electron/js2c/browser_init:185:1685)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:165:14118)
    at EventEmitter.emit (node:events:527:28)

**Comment by dwilt** [comment]
So, I noticed this started happening as I added more and more custom commands.. has anyone else noticed that pattern or is that unrelated?

**Comment by andrii-lundiak** [comment]
Closed because what? Fixed in scope if Cypress `v12.17.1`?

**Comment by nagash77** [comment]
@andrii-lundiak looking at the PR that closed this issue it looks like that was merged into develop and that will be going out with the 12.18.0 release which is scheduled for Tuesday July 18th at the moment.
