### ISSUE TITLE
Component testing broken with NextJS 13.2.1

### ISSUE THREAD

**Issue by jamesopti** [cypress-io/cypress#25951]
### Current behavior

Component tests run fine on NextJS v13.1.1, but fail to compile on v13.2.1

The error received is unable to find module, where the module resolution relies on the `tsconfig` basePath setting in `/cypress/tsconfig.json`

Component test cypress config settings:

```
component: {
    devServer: {
      framework: 'next',
      bundler: 'webpack',
    },
}
```

### Desired behavior

Component tests should compile and run using the `tsconfig.json` settings.

Possibly related NextJS change/update: https://github.com/vercel/next.js/pull/45455

### Test code to reproduce

Run any component test that uses a custom cypress `tsconfig` with NextJS v13.2.1

### Cypress Version

latest

### Node version

v16.3

### Operating System

MacOSX And Github Actions Linux

**Comment by jamesopti** [comment]
This issue looks to be the same: https://github.com/cypress-io/cypress/issues/25943

**Comment by lmiller1990** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Component-Testing-606e43bbf1b3b20013c142c1/issues/cypress-io/cypress/25951?planning-poker) with Zenhub @astone123 @marktnoonan @mike-plummer @warrensplayer @ZachJW34

**Comment by lmiller1990** [comment]
Thanks for the bug report (and tracking down the actual change, by the looks of it!). We will look at this in the next week or so.

**Comment by ZachJW34** [comment]
The Next update added a new property to the [getBaseWebpackConfig](https://github.dev/vercel/next.js/blob/69fe4eee39747861bc7bc306ac5ab1a2e5786596/packages/next/src/build/webpack-config.ts#L623) that we utilize for sourcing the Next config. The new `jsconfig` option sets up the ts aliases.

They export a [loadProjectInfo](packages/next/src/build/webpack-config.ts) function that grabs the `{ts,js}.config.json` we could utilize, or use the [load-jsconfig.ts](https://github.dev/vercel/next.js/blob/69fe4eee39747861bc7bc306ac5ab1a2e5786596/packages/next/src/build/load-jsconfig.ts#L40) directly

**Comment by OleksiiKachan** [comment]
can we have a release with this?

**Comment by astone123** [comment]
@OleksiiKachan this will be included in release 12.8.0 which should be released today

**Comment by franzwarning** [comment]
Just updated to 12.8 and I'm getting an error that cypress can't resolve my modules that I import w/ absolute paths:
```
Module not found: Can't resolve 'src/utils/date'
```

This was working before our Next 13.2 update... any ideas?

**Comment by astone123** [comment]
@franzwarning are you able to share your ts/js config?

**Comment by franzwarning** [comment]
> @franzwarning are you able to share your ts/js config?

```
{
  "compilerOptions": {
    "target": "es6",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "preserve",
    "incremental": true,
    "baseUrl": ".",
    "plugins": [
      {
        "name": "next"
      }
    ]
  },
  "include": [
    "**/*.ts",
    "**/*.tsx",
    ".next/types/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by franzwarning** [comment]
@astone123 fixed by adding:
```
"paths": {
      "src/*": [
        "src/*"
      ],
      "mocks/*": [
        "mocks/*"
      ],
      "public/*": [
        "public/*"
      ],
    },
```

but I shouldn't really have to do that right? idk y'all know better than me!

**Comment by astone123** [comment]
@franzwarning my understanding is that you should not have to add the paths to your config, the modules should be resolved using `baseUrl`. Can you help me understand when this stopped working? 

Next 13.2 + Cypress 12.7 and previous ✅ ?
and
Next 13.2 + Cypress 12.8 ❌ ?

**Comment by franzwarning** [comment]
✅ Next 13.1.6 Cypress 12.7
❌ Next 13.2.x Cypress 12.7 (when I started following this issue) (I forget what broke the first time -- might have been the same issue?)
❌ Next. 13.2.x Cypress 12.8

Hope that helps.

**Comment by OleksiiKachan** [comment]
I had `"*"` alias. in addition to `["src/*"]` had to add node_modules
so my alias looks like `"*": ["src/*", "node_modules"]`

```
"next": "^13.2.4",
"cypress": "^12.8.0",
```

now all works for me

**Comment by jamesopti** [comment]
I can confirm this is still broken for me too. the `baseUrl` setting is not being respected.

tsconfig.json:

```
{
  "compilerOptions": {
    "baseUrl": "./src",
    "paths": {
      "publicImages/*": ["../public/images/*"]
    },
    "target": "es2015",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "sourceMap": true,
    "isolatedModules": true,
    "noImplicitReturns": true,
    "importHelpers": true,
    "strictNullChecks": true,
    "suppressImplicitAnyIndexErrors": true,
    "noUnusedLocals": false,
    "allowSyntheticDefaultImports": true,
    "downlevelIteration": true,
    "strictBindCallApply": true,
    "jsx": "preserve",
    "incremental": true
  },
  "exclude": ["node_modules", "cypress", "./cypress.config.ts"],
  "include": [
    "next-env.d.ts",
    "fontawesome.d.ts",
    "**/*.ts",
    "**/*.tsx",
    "src/test/jest-setup.ts",
    "jest.config.ts"
  ]
}

```

**Comment by lmiller1990** [comment]
Looks like our fix didn't work. We will look into this now.

**Comment by yosi1314** [comment]
The version update or the paths workaround didnt work for me. Any updates?

**Edit - Adding `NODE_PATH=src` solved it for me

**Comment by lmiller1990** [comment]
We will be looking into this in the next week or two! Sorry about the wait.

**Comment by jamesopti** [comment]
> We will be looking into this in the next week or two! Sorry about the wait.

This doesn't inspire a lot of confidence in the Component testing product 😕

**Comment by lmiller1990** [comment]
I'm sorry this isn't working for you right now. We can definitely add a regression test as part of this fix, so it is less likely to happen in the future. We will take a look next week.

If you'd like to take a stab at fixing it before then, I can help with reviewing and releasing the fix.

The Next.js specific code is in this file: https://github.com/cypress-io/cypress/blob/develop/npm/webpack-dev-server/src/helpers/nextHandler.ts. Next.js does _not_ expose a public API for their configuration, which is why it can break in a minor version.

Any ideas on the correct fix? Should we just add `NODE_PATH=<your_base_url>`? Does the `NODE_PATH` fix work for you @jamesopti?

**Comment by lmiller1990** [comment]
I am working on this. It works in Next 13.0.0 but not in 13.2.1. I will debug more, but I think the issue title is a bit of a red herring - I think the breakage was earlier.

✅ 13.1.4 
✅ 13.1.5
✅ 13.1.6
✅ 13.1.7-canary.0
✅ 13.1.7-canary.1
✅ 13.1.7-canary.2
✅ 13.1.7-canary.3
✅ 13.1.7-canary.4
✅ 13.1.7-canary.6
❌ 13.1.7-canary.7
...
❌ next@13.1.7-canary.21
❌  13.1.7-canary.32
❌ 13.2.0

**Comment by jamesopti** [comment]
@lmiller1990 Thanks for the update and sorry for my slightly snarky response earlier.

I didn't realize this was powered by an unsupported NextJS API, so totally understand the challenge. Next is a great platform but their support for testing & CI leaves something to be desired.

I'm happy to test a `NODE_PATH` fix if thats a workaround!

**Comment by lmiller1990** [comment]
@jamesopti all good, no-one likes it when their thing randomly breaks. I updated my post above - I found the issue was introduced in 13.1.7-canary.7. This greatly minimizes the surface area, I am sure we can fix this very soon 👍 

You could use the work around for the next week or so, I'm fairly confident we will ship *the* fix in the next Cypress version.

**Comment by lmiller1990** [comment]
Diff... https://github.com/vercel/next.js/compare/v13.1.7-canary.6...v13.1.7-canary.7. Lots of files but mostly static content. Some interesting parts:

- https://github.com/vercel/next.js/compare/v13.1.7-canary.6...v13.1.7-canary.7#diff-5f441142eb8ba9bcba515aa36fbc420a113307bd191e54a4e9e6c43529fc2613R587 (references `resolvedBaseUrl`)

Here we go - [this grabs the `baseUrl`](https://github.com/vercel/next.js/blame/400ccf7b1c802c94127d8d8e0d5e9bdf9aab270c/packages/next/src/build/load-jsconfig.ts#L88-L92) I am not sure why we don't get this for free, since we just use the same webpack config as Next.js, but I think we can find a fix for this: 

This line was added in Next.js 12.x, but it wasn't actually added to the `webpackBaseConfig` via spreading `...info` until 13.1.7-canary.7. [here](https://github.com/vercel/next.js/compare/v13.1.7-canary.6...v13.1.7-canary.7#diff-0260dbfc6a047be5877f047fb9f7205b57920663963f0dadd6fffe912b6d386bR491-R495). That's why it broke - I wonder if we load the webpack config in a different fashion, prior to `...info` getting spread, updating the `baseUrl`.

**Comment by lmiller1990** [comment]
Hi friends, I fixed it! https://github.com/cypress-io/cypress/pull/26399 /cc @jamesopti @OleksiiKachan @yosi1314. You can test it out using a pre-release binary: https://github.com/cypress-io/cypress/commit/6a37c4ad0a427d2857964e0d6aab709f5dc281ac#comments

Next release is *tomorrow*, I'll get some 👀 and ✅ so this can make it in 😎

**Comment by jamesopti** [comment]
Thanks for the fix @lmiller1990 - Looks like a release didn't happen last Monday.

Can we expect one today?

**Comment by mike-plummer** [comment]
@jamesopti Sorry about the miscommunication, @lmiller1990 was off by one week on our release cadence (and he's in Australia so all the days are off-by-one). Our next release is planned for tomorrow (Tuesday).

**Comment by lmiller1990** [comment]
@jamesopti did you try the pre-release? You can start using this right now: https://github.com/cypress-io/cypress/commit/bf7771f457913c88cdf7eb10e349e0f8d5eec22e#comments and then upgrade to the mainline release when it comes out.

Those pre-release binaries expire eventually, but it's live for me right now.

**Comment by jamesopti** [comment]
> @jamesopti did you try the pre-release? You can start using this right now: [bf7771f#comments](https://github.com/cypress-io/cypress/commit/bf7771f457913c88cdf7eb10e349e0f8d5eec22e#comments) and then upgrade to the mainline release when it comes out.
> 
> Those pre-release binaries expire eventually, but it's live for me right now.

Thanks for pointing out how easy it is to test with these!

I confirmed that this release passes all tests in our suite. Will wait for tomorrows deploy.

**Comment by dbrxnds** [comment]
When exactly can we expect this release?

**Comment by marktnoonan** [comment]
Sorry for the wait. We typically release every two weeks on a Tuesday, but it's possible to get off that cadence every now and then, as we are here.

This is where the pre-release binaries come in handy. They last for 30 days. Please don't be blocked on your side waiting for the official release, if you need to start using this now, you can switch to the binary that has the fix now (https://github.com/cypress-io/cypress/issues/25951#issuecomment-1493689132), and then switch back to the new version of Cypress when it comes out.
