### ISSUE TITLE
Cypress hangs when running multiple spec files but not one by one

### ISSUE THREAD

**Issue by mauriciabad** [cypress-io/cypress#26688]
### Current behavior

When I run 4 specific tests in headless mode, cypress freezes when starting to run the 2nd or 3rd spec file.

The same tests pass in this conditions:
- If you run the tests with `cypress open`.
- If you run them individually, deleting the other 3 tests.

The last thing I can see in the console is:
```log

────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  home.spec.ts                                                                    (3 of 4)

Timed out waiting for the browser to connect. Retrying...

Timed out waiting for the browser to connect. Retrying again...

The browser never connected. Something is wrong. The tests cannot run. Aborting...

The browser never connected. Something is wrong. The tests cannot run. Aborting...
Warning: We failed processing this video.

This error will not affect or change the exit code.

TimeoutError: operation timed out
    at afterTimeout (/home/runner/.cache/Cypress/12.11.0/Cypress/resources/app/node_modules/bluebird/js/release/timers.js:46:19)
    at Timeout.timeoutTimeout [as _onTimeout] (/home/runner/.cache/Cypress/12.11.0/Cypress/resources/app/node_modules/bluebird/js/release/timers.js:76:13)
    at listOnTimeout (node:internal/timers:559:17)
    at process.processTimers (node:internal/timers:502:7)

  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        0                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     0 seconds                                                                        │
  │ Spec Ran:     home.spec.ts                                                                     │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
```

### Desired behavior

That tests pass.

In case this is a problem with my code. I expect that cypress crashes gracefully with an error message, instead of just hanging.

### Test code to reproduce

**https://github.com/mauriciabad/wordspy/pull/23**

I can't isolate the test that makes the error (When I isolate the tests, they work), so this is the minimum reproducible version I'm able to give you.

You can check the CI to see the failing tests.

### Cypress Version

12.11.10

### Node version

18.16.0

### Operating System

Ubuntu 22.04.2 LTS

### Debug Logs

https://raw.githubusercontent.com/mauriciabad/wordspy/cypress-issue-report/logs.txt

(They are too long, github doesn't let me submit)

### Other

I don't know if it's related but, I saw this lines in the debug logs:
```log
"Uncaught Error: Something went terribly wrong and we cannot proceed. We expected to find the global Cypress in the parent window but it is missing. This should never happen and likely is a bug. Please open an issue."
```
```log
cypress:server:browsers killing browser process
```
```log
cypress:server:browsers browser process killed
```

**Comment by chrisbreiding** [comment]
Could you try using the [official github action](https://github.com/marketplace/actions/cypress-io) and see if that yields a better result? If not, maybe try running the tests in Chrome (instead of the default, Electron)?

**Comment by mauriciabad** [comment]
I tried using the official GitHub action with electron, and it doesn't work. But using chrome works.

This may look like using chrome solves the issue, but the bug is still there. The code is right, and tests should be passing in both browsers.

#### Logs
Electron: https://github.com/mauriciabad/wordspy/actions/runs/4973594173/jobs/8899535122?pr=23
Chrome: https://github.com/mauriciabad/wordspy/actions/runs/4973608122/jobs/8899557606?pr=23

**Comment by chrisbreiding** [comment]
Thanks for trying that out. Tests should definitely be passing in both browsers. It's useful to know that it might be isolated to an issue with Electron.

I'm going to forward this ticket to the appropriate team. They will evaluate the priority of this ticket and consider their capacity to pick it up. Please note that this does not guarantee that this issue will be resolved. The ticket will indicate status changes during evaluation, so we ask that you please refrain from asking for updates. Thanks!

**Comment by nloutadeo** [comment]
@chrisbreiding  This is similarly encountered in Firefox. Hope you check it there as well.

**Comment by joseph-luketelo** [comment]
@chrisbreiding  Was this resolved, I am facing the same error on Firefox!

**Comment by phoebejaffe** [comment]
I'm also now facing this error when using Firefox. It started happening on its own in the last 24 hours, and only on about half of our tests in any given run.

**Comment by akepley0280** [comment]
> I'm also now facing this error when using Firefox. It started happening on its own in the last 24 hours, and only on about half of our tests in any given run.

We are also seeing this after installing Firefox 124. Always on multiple tests running synchronously, always on Firefox.  On CI, first test in the set runs fine, then this failure at the start of the second test.

```There was an error reconnecting to the Chrome DevTools protocol. Please restart the browser.

Error: connect ECONNREFUSED 127.0.0.1:32853
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
Test run failed, code 1
More information might be available above
Cypress module has returned the following error message:
Could not find Cypress test run results
Error: Could not find Cypress test run results
```


On local cypress run, the second test has the following:
```Still waiting to connect to Firefox, retrying in 1 second (attempt 18/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 19/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 20/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 21/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 22/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 23/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 24/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 25/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 26/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 27/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 28/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 29/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 30/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 31/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 32/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 33/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 34/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 35/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 36/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 37/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 38/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 39/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 40/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 41/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 42/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 43/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 44/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 45/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 46/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 47/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 48/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 49/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 50/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 51/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 52/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 53/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 54/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 55/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 56/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 57/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 58/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 59/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 60/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 61/62)
Still waiting to connect to Firefox, retrying in 1 second (attempt 62/62)
Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 50 seconds.

This usually indicates there was a problem opening the Firefox browser.

The CDP port requested was 57510.

Error: Could not find url target in browser about:blank. Targets were []
    at <embedded>:4489:71485
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async n (<embedded>:4489:70649)
    at async Object.connectToNewSpec (<embedded>:4489:166476)
    at async Object.O (<embedded>:4495:7500)
    at async Object.connectToNewSpec (<embedded>:4495:25721)
    at async v.relaunchBrowser (<embedded>:4561:147231)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by mschile** [comment]
The Firefox 124 issue is being resolved with https://github.com/cypress-io/cypress/pull/29179 and should be released soon.

**Comment by ryguy432** [comment]
I am having a similar issue running against all four browsers. If I run a suite of tests then it freezes as it's passing one test and starting another. If I run those same tests individually then they run just fine, it's just running more than one at a time. If I'm using the GUI, then the whole thing freezes, I can't even end the tests through the browswer or the gui/app, I have to kill those processes. Everything was working fine, just stopped working out of no where. 
At the time I was using 12.17.4, I've since updated to 13.13.3 and it still happens across all browsers. 
Mac Sonoma 14.6.1
Node 18.5.0 and also tried 20.10.0

**Comment by vedmant** [comment]
I'm having the same issue, very random, sometimes tests failing when runnign all, sometimes cypress just hangs indefinitely, but all tests run ok when I specify single `--spec`. 

`"cypress": "^13.17.0"`

**Comment by Deadlytest** [comment]
Hi there. I'm having a problem running headless mode with Electron. It stops running because it crashes.

I already added the following to `cypress.config.js`:

```javascript
config.experimentalMemoryManagement = true;
        config.numTestsKeptInMemory = 0;
        // Solo para headless (cypress run)
        config.video = false;
        config.retries = 2;
        config.browsers = [{
          name: 'chrome',
          family: 'chromium',
          channel: 'stable',
          displayName: 'Chrome',
          isHeaded: false,
          isHeadless: true,
          launchOptions: {
            args: [
              '--disable-gpu',
              '--no-sandbox',
              '--disable-dev-shm-usage',
              '--disable-software-rasterizer',
              '--headless=new',
              '--memory-pressure-off',  // Desactiva la presión de memoria
              '--js-flags="--max-old-space-size=8192"', // Aumenta el límite de memoria para V8
              '--disable-extensions',    // Deshabilita extensiones
              '--disable-notifications', // Deshabilita notificaciones
              '--disable-infobars'      // Deshabilita infobars
            ]
          }
```
Yet the problem is still happening

```console
Configuration module and fields
    √ should create custom module successfully (35852ms)
    √ should add custom fields (38413ms)
    √ should create rules for fields (37983ms)
    √ should allow to configure view of the module (21768ms)

We detected that the Electron Renderer process just crashed.

We have failed the current spec but will continue running the next spec.

This can happen for a number of different reasons.

If you're running lots of tests on a memory intense application.
  - Try increasing the CPU/memory on the machine you're running on.
  - Try enabling experimentalMemoryManagement in your config file.
  - Try lowering numTestsKeptInMemory in your config file during 'cypress open'.

You can learn more here:

https://on.cypress.io/renderer-process-crashed
```

However, this doesn't happen when running headless with Chrome.
