### ISSUE TITLE
3.1.1 regression: cookie can't be set when visiting local devserver

### ISSUE THREAD

**Issue by KoenCa** [cypress-io/cypress#2724]
I was just following the tutorial and trying to setup simple tests for our app and an error stopped me.

### Current behavior:
The very simple test case:
```javascript
describe("Login", function() {
  it("Goes to login page", function() {
    cy.visit("https://localhost:8443");
  });
});
```

Generates the following error in the test runner:
```
CypressError: cy.visit() failed trying to load:

https://localhost:8443/

We attempted to make an http request to this URL but the request failed without a response.

We received this error at the network level:

  > TypeError: Cannot set property 'url' of undefined

Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer

The stack trace for this error is:

TypeError: Cannot set property 'url' of undefined
    at Object.setCookie (/Users/koen/Library/Caches/Cypress/3.1.1/Cypress.app/Contents/Resources/app/packages/server/lib/request.js:91:20)
    at addCookie
```

### Desired behavior:

I want Cypress to open my page so I can start writing tests 😄 

### Steps to reproduce:

1. Add Cypress to a project or create a Cypress project
2. Just add a single file with the test case above
3. Run the test runner with that test.

Reproduce is probably going to be hard, because visiting a production version of our app with Cypress worked correctly.

### Versions

- Cypress: 3.1.1
- Chrome: 70
- OS: macOS High Sierra

### Workaround

I first asked a question about this on the Gitter channel and downgrading to 3.1.0 made the test case above work and my page was loaded correctly.

### Extra

I think something goes wrong here: [request.coffee](https://github.com/cypress-io/cypress/blob/25bdc955cd39e50766e963a0f478934c329bc0cd/packages/server/lib/request.coffee#L70)

**Comment by jennifer-shehane** [comment]
Hey @KoenCa, we'll need a reproducible example. Following your steps to reproduce will not reproduce the problem without having you app locally running - which you did not provide.

**Comment by mcarlotta** [comment]
Downgrading Cypress back to 3.1.0 fixed our issue

**Comment by KoenCa** [comment]
@brian-mann I don't know an external site that causes the problem. Production instances of our app work while the local version doesn't and there aren't any differences in what is send back by the webserver. I'm not using `cy.setCookie`, the code that I provided was the only test code I have which made it fail. I can confirm that both `cy.visit()` and `cy.request()` failed.

Under the hood nothing special is happening. It just goes to our login page without any redirects.

**Comment by agcooke** [comment]
We are also seeing the same issue on our builds. Locking to 3.1.0 fixed it.

**Comment by federicomaffei** [comment]
Our team had the same issue when calling `setCookie` since the release of `3.1.1`. A few notes in the hope it can help with troubleshooting:
* running Cypress against a locally running version of the system under test **works**
* running Cypress from a Docker container against the system under test running on another Docker container **fails** with the message `> TypeError: Cannot set property 'url' of undefined`.
* running Cypress from a Docker container against a production deployed version of the system under test **fails**  with the message `> TypeError: Cannot set property 'url' of undefined`.

Can confirm that downgrading to `3.1.0` eliminates the behaviour.
Thanks for the good work on Cypress.

**Comment by rshafakian** [comment]
We were having this same issue while running 3.1.1.    Then I came across something that I'm wondering if you guys are as well.  My build site is through Jenkins and when the url is something like my_test_branch.mysite.com it fails, but if my url is mytestbranch.mysite.com then it passes.  Can anyone else confirm?

**Comment by mcarlotta** [comment]
@rshafakian we have a similar setup to the one you mentioned. However, even our local tests started failing after update

**Comment by rshafakian** [comment]
@mcarlotta yes our local is running 3.1.0 so that passes.  build branch is using 3.1.1, but rolled back to 3.1.0 so it passes.  but when our build branch has a url without any dashes or underscores it still passes on 3.1.1 (e.g. 'test.domain.com` instead of 'app-test.domain.com').  Not sure if this is the case for everyone else as well.  can you setup your url that way to see if it still fails?  might just get closer to solving the problem if that's the case.

**Comment by brian-mann** [comment]
I believe this is happening when a server sends back invalid cookies, but I'm working on trying to reproduce it first. I understand how this is happening and should be relatively simple to fix.

**Comment by jennifer-shehane** [comment]
The code for this is done, but this has yet to be released. We'll update this issue and reference the [changelog](https://on.cypress.io/changelog) when it's released.

**Comment by brian-mann** [comment]
Released in [`3.1.2`](https://docs.cypress.io/guides/references/changelog.html#3-1-2).

**Comment by brandonb927** [comment]
Can confirm this is fixed in 3.1.2 in our builds 🎉 Thanks @brian-mann @jennifer-shehane!

**Comment by mcarlotta** [comment]
Same for us as well. Thanks!

**Comment by jeff-h** [comment]
Unfortunately both 3.1.1 **and** 3.1.2 break my tests (which work fine under 3.1.0).

The [initial issue description](https://github.com/cypress-io/cypress/issues/2724#issue-377847033) describes the following error:
`TypeError: Cannot set property 'url' of undefined at Object.setCookie`

The [other error in this thread](https://github.com/cypress-io/cypress/issues/2724#issuecomment-436376746) is:
`RequestError: TypeError: Cannot set property 'url' of undefined at new RequestError`

I'm getting this latter one, so I'm unsure whether it's due to cookies or not.

I'm testing Drupal 7 which supplies a session cookie like the following:

`SSESSc6eea7caf5ccca2bfa189816e5172697=Qd3UYdcybAYUkqyDWNzEk0NWbEa5A83K7mbhMA00wL4; expires=Fri, 14-Dec-2018 04:30:18 GMT; Max-Age=2000000; path=/; domain=.myserver.local; secure; HttpOnly`

Perhaps that's invalid (I don't know how to tell). It does work though; in 3.1.0 it's enough to allow Cypress to "log in" to my app.

In 3.1.1 I got the same error as above (`RequestError: TypeError: Cannot set property 'url' of undefined at new RequestError`). In 3.1.2 I no longer get any error from Cypress, but my tests don't log in, and the session cookie is not saved.

I also tried telling Drupal to remove `HttpOnly`, thinking that it might be causing an issue with Javascript accessing the cookie, but just get the same result.

**Comment by twslade** [comment]
Fixed for us as well!

**Comment by jm2242** [comment]
Still looks like we're getting the same error with `3.1.3`:
`{ [Error: Failed to parse or set cookie named "current_version".] name: undefined }`

**Comment by jennifer-shehane** [comment]
Hey @jm2242 could you open a new issue detailing your test code and how you are setting cookies. A reproducible example would be best.

**Comment by jm2242** [comment]
Okay will open a new issue with details from https://github.com/cypress-io/cypress/issues/1321

**Comment by jeff-h** [comment]
Unfortunately v3.1.3 does not fix the issue I described in https://github.com/cypress-io/cypress/issues/2724#issuecomment-440503823 for me. I'm stuck on 3.1.0, as no subsequent versions manage to log into my Drupal instance.

**Comment by jennifer-shehane** [comment]
Hi @jeff-h, could you open a new issue? Since several users have confirmed their issue was resolved with the 3.1.2 release - we will be considering any issues persisting through 3.1.2 as separate issues (or edge cases of this issue) that we'd like to address directly. 

We will be closing this issue to further discussion as this specific use case is seen as resolved. Please open a new issue if you are experiencing similar behavior.
