### ISSUE TITLE
Cypress only runs the first test in the test suite and does not proceed further

### ISSUE THREAD

**Issue by sambit-senapati** [cypress-io/cypress#29494]
### Current behavior

Cypress runs only the first test in the  test suite and does not run the rest of the tests (the time keeps going but it doesn't proceed to the next test).

Example spec:

```js
describe('Create Tests', () => {
  context('Submitting form', () => {
     beforeEach(() => {
      cy.login(testMainUserCreds.username, testMainUserCreds.password)
    })
    it('test case 1', () => {}
    it('test case 2', () => {
  }
 }
```

I have verified the test suite by running in my colleagues laptop and it runs all of the test suite but the same test suite does not run fully for me

Below steps have been performed,
- cleared cookies
- re-installed cypress

### Desired behavior
Cypress should run all of the tests in the test suite

### Test code to reproduce

```js
describe('Create Tests', () => {
  context('Submitting form', () => {
     beforeEach(() => {
      cy.login(testMainUserCreds.username, testMainUserCreds.password)
    })
    it('test case 1', () => {}
    it('test case 2', () => {
  }
 }
`
```

<img width="434" alt="Screenshot 2024-05-09 at 3 34 08 PM" src="https://github.com/cypress-io/cypress/assets/122248039/c34c566b-99c6-41e2-abc2-06aed9468355">

### Cypress Version

13.6.4

### Node version

v18.14.0

### Operating System

macOS 14.1.1

**Comment by jennifer-shehane** [comment]
@sambit-senapati Could you please update to the latest Cypress and try rerunning? We did have an issue with this in a previous version that we fixed.

**Comment by sambit-senapati** [comment]
> @sambit-senapati Could you please update to the latest Cypress and try rerunning? We did have an issue with this in a previous version that we fixed.

sure, will update and let you know, thanks

**Comment by sambit-senapati** [comment]
> @sambit-senapati Could you please update to the latest Cypress and try rerunning? We did have an issue with this in a previous version that we fixed.

Hey @jennifer-shehane , upgrading to the latest version fixed the issue, thanks

**Comment by sk15000** [comment]
@jennifer-shehane for me it is still reproducible:

I am getting the following error, when running the tests through Bitbucket pipeline on Electron, Chrome, Edge, all Cypress versions above 13.3.1 headless. Tried different Docker images as well.

Only the first one or 2 tests are running, and then it stops.

```
CypressError: Timed out after waiting `60000ms` for your remote page to load.
Your page did not fire its `load` event within `60000ms`.
You can try increasing the `pageLoadTimeout` value in `cypress.config.js` to wait longer.
Browsers will not fire the `load` event until all stylesheets and scripts are done downloading.
When this `load` event occurs, Cypress will continue running commands.
```

Example not working config (Bitbucket + locally) headless:
  │ Cypress:        from 13.3.2 to 13.9.0                                                                         │
  │ Browser:        Chrome 114 (headless)                                                          │
  │ Node Version:   v18.16.0 (/usr/local/bin/node)  
  
  
 Example working config (headless)
  │ Cypress:        13.3.1                                                                         │
  │ Browser:        Chrome 124 (headless)                                                          │
  │ Node Version:   v20.12.2 (/usr/local/bin/node)  
  
  
  * But when it runs locally, it has issues with the service workers, so I have to unregister the manually each time.
  * Every other Cypress version after this is not working with the headless Chrome

**Comment by jennifer-shehane** [comment]
@sk15000 Please open a new issue with a reproducible example. The issue you're describing is different from the original one posted here.
