### ISSUE TITLE
Add support for testing chrome extensions

### ISSUE THREAD

**Issue by pipsk** [cypress-io/cypress#298]
**Description**
*Add support for testing chrome extensions.*

**Code**
`cy.visit('chrome-extension://ojdhgjfbbonanlpdejcbmiledkcedbdo/popup.html');`

**Additional Info**
Right now, it doesn't navigate to url and throws error with message:
'Sorry, we could not load: chrome-extension://ojdhgjfbbonanlpdejcbmiledkcedbdo/popup.html' 

Since you get questions about testing chrome extensions, maybe include more verbose error message or info that you don't support that yet.

**Comment by brian-mann** [comment]
Fixed by https://github.com/cypress-io/cypress/pull/1078.

**Comment by brian-mann** [comment]
Released in [`1.3.0`](https://docs.cypress.io/guides/references/changelog.html#1-3-0).

**Comment by kslonka** [comment]
Can someone provide an example of loading a custom unpacked chrome extension?

**Comment by udarafossdev** [comment]
@kslonka 
See if this helps :)
https://docs.cypress.io/api/plugins/browser-launch-api.html#

**Comment by JulianG** [comment]
That example loads the extension into the Cypress chrome browser.
But I believe the issue persists: the call to `cy.visit` fails to navigate to the specified `chrome-extension://dsadsadwhateverdsadasd/index.html`

**Comment by JulianG** [comment]
I can see the test page is `http://localhost:54493/__/#/tests/integration/visit.spec.js` and it contains an iframe with the page I'm testing, which uses `chrome-extension://` protocol. I'm not sure that would ever work.
