### ISSUE TITLE
Tests always failling in GitHub Actions

### ISSUE THREAD

**Issue by fabu1985** [cypress-io/cypress#30183]
### Current behavior

  This is my job :
  ```yml
  cypres_test:
    runs-on: ubuntu-22.04
    name: Cypress Tests
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      # Setup Yarn Berry
      - name: Set up Yarn
        run: |
          npm install -g yarn@berry
          yarn set version berry
          yarn --version

      # Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CALM_SEA_0E6F37A10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist" # Built app content directory - optional
          app_build_command: "yarn build:mocked" # Comando de build personalizado
          skip_app_build: false
          skip_api_build: true
  
      # Run Cypress tests
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        env: 
          EEO_AUTOMATION_BASE_URL: https://calm-sea-0e6f37a10-139.centralus.3.azurestaticapps.net
        with:
          config: 'baseUrl=https://calm-sea-0e6f37a10-139.centralus.3.azurestaticapps.net'
          command: yarn automation:e2e
          wait-on: 'https://calm-sea-0e6f37a10-139.centralus.3.azurestaticapps.net'
          wait-on-timeout: 110
```

So, the result is always the same

```
AssertionError: Timed out retrying after 0ms: Expected to find element: `[data-testid^="welcomeHeader"]`, but never found it.
```

### Test code to reproduce

https://github.com/fabu1985/algo/actions/runs/10704642103/job/29678128833?pr=12

### Cypress Version

13.14.1

### Node version

20.14.0

### Operating System

ubuntu

### Other

I check it running a simple test against Google page, and worked ok. It´s means the latest versions for cypress and libraries updated, are not the problem, aparently.
I harcoded the baseurl and the problem still happening.

I´ll appreciatte u any idea o suggestion... thanks!!!

**Comment by jennifer-shehane** [comment]
There's not much for us to look into on our side for this. This element is not being found for some reason. [Test Replay](https://docs.cypress.io/guides/cloud/test-replay) is a good way to debug failures in CI as it replays entirely what happened where you can visually see it.

**Comment by MikeMcC399** [comment]
@fabu1985 

See https://github.com/cypress-io/github-action/blob/master/README.md#custom-test-command

![image](https://github.com/user-attachments/assets/1a9f81db-c7e9-485a-9783-d8c5e093a153)

Using `command` switches off most of the functionality of the action. I can't tell if this is your problem however.

Take a look at the examples in https://github.com/cypress-io/github-action/blob/master/README.md to see how the action is intended to be used.

https://github.com/fabu1985/algo/actions/runs/10704642103/job/29678128833?pr=12 is not readable: 404 error - probably a private repository. You need to make it public if you want anybody to look at it.

**Comment by fabu1985** [comment]
> There's not much for us to look into on our side for this. This element is not being found for some reason. [Test Replay](https://docs.cypress.io/guides/cloud/test-replay) is a good way to debug failures in CI as it replays entirely what happened where you can visually see it.

I debugged it, I tried visiting the Google hompeage and everything is ok. The problem it´s only with my tests against the builded page. Locally, they are running succesfully

**Comment by fabu1985** [comment]
> @fabu1985
> 
> See https://github.com/cypress-io/github-action/blob/master/README.md#custom-test-command
> 
> ![image](https://private-user-images.githubusercontent.com/66998419/364447129-1a9f81db-c7e9-485a-9783-d8c5e093a153.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0NzczODYsIm5iZiI6MTcyNTQ3NzA4NiwicGF0aCI6Ii82Njk5ODQxOS8zNjQ0NDcxMjktMWE5ZjgxZGItYzdlOS00ODVhLTk3ODMtZDhjNWUwOTNhMTUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDE5MTEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwY2U4ZWZmNjhmYzI5YjBiNzNhMmYzMTg5MDE1MjhjMGM1NTNhMGU2YmQ5MzU4NWZlZWJjNWUzYmNmNTcyMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dEiaN5I5Bli7InjQt4TwqhB-vvEnD-iYkCQiz6VNKcE)
> 
> Using `command` switches off most of the functionality of the action. I can't tell if this is your problem however.
> 
> Take a look at the examples in https://github.com/cypress-io/github-action/blob/master/README.md to see how the action is intended to be used.
> 
> https://github.com/fabu1985/algo/actions/runs/10704642103/job/29678128833?pr=12 is not readable: 404 error - probably a private repository. You need to make it public if you want anybody to look at it.

@MikeMcC399 I created a test to check the Google Homepage, and it´s ran ok. The tests thar are running against the builded page  still failling.

**Comment by MikeMcC399** [comment]
@fabu1985 
> I created a test to check the Google Homepage, and it´s ran ok. The tests thar are running against the builded page still failling.

There is no new information in this issue to allow further analysis.

The only information is the error message:

```
AssertionError: Timed out retrying after 0ms: Expected to find element: `[data-testid^="welcomeHeader"]`, but never found it.
```

**Comment by fabu1985** [comment]
> @fabu1985
> 
> > I created a test to check the Google Homepage, and it´s ran ok. The tests thar are running against the builded page still failling.
> 
> There is no new information in this issue to allow further analysis.
> 
> The only information is the error message:
> 
> ```
> AssertionError: Timed out retrying after 0ms: Expected to find element: `[data-testid^="welcomeHeader"]`, but never found it.
> ```

@MikeMcC399 let me tell u that I did some changes, like as:
- increase the timeout.
- use 'id' or some css 'path', instead data-testid
not succes.

This is the static azure page, you can see that the page is ok: 
https://calm-sea-0e6f37a10-139.centralus.3.azurestaticapps.net/

This is the particular command that I use
`"automation:e2e": "cypress run --browser chrome --headless --spec 'automation/cypress/e2e/eventCards.feature'"`

Here the last GitHubActions output
![image](https://github.com/user-attachments/assets/e0c1f909-b43e-42d9-9825-2fc75f31af19)

**Comment by MikeMcC399** [comment]
@fabu1985 

It seems that you are having a problem using `cypress-cucumber-preprocessor`. Which version are you using?

When I view https://calm-sea-0e6f37a10-139.centralus.3.azurestaticapps.net/ in Google Chrome, it first displays content, then it displays only a blank page.

**Comment by fabu1985** [comment]
> @fabu1985
> 
> It seems that you are having a problem using `cypress-cucumber-preprocessor`. Which version are you using?
> 
> When I view https://calm-sea-0e6f37a10-139.centralus.3.azurestaticapps.net/ in Google Chrome, it first displays content, then it displays only a blank page.

I´m use _"cypress-cucumber-preprocessor": "^4.3.1"_
Why do you think that is Cucumber version the problem? I left this idea, ´cause the test that check the logo on the google homepage, passed ok. or am I confused?
regarding the blank page, maybe was ´cause I was running the jobs here. You can check it now mad you should not have problems.

**Comment by MikeMcC399** [comment]
@fabu1985 

> I´m use "cypress-cucumber-preprocessor": "^4.3.1"

This is an old version which has been replaced by [@badeball/cypress-cucumber-preprocessor](https://www.npmjs.com/package/@badeball/cypress-cucumber-preprocessor). See https://github.com/badeball/cypress-cucumber-preprocessor/issues/689

This topic is however outside of the scope of a Cypress bug report in this issue list.

**Comment by fabu1985** [comment]
> @fabu1985
> 
> > Estoy usando "cypress-cucumber-preprocessor": "^4.3.1"
> 
> Esta es una versión antigua que ha sido reemplazada por [@badeball/cypress-cucumber-preprocessor](https://www.npmjs.com/package/@badeball/cypress-cucumber-preprocessor) . Ver [badeball/cypress-cucumber-preprocessor#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)
> 
> Sin embargo, este tema está fuera del alcance de un informe de errores de Cypress en esta lista de problemas.

ok, understood. My question is, why do you think that the problem is cucumber-preprocessor?

**Comment by MikeMcC399** [comment]
@fabu1985

> ok, understood. My question is, why do you think that the problem is cucumber-preprocessor?

There isn't enough information available in this issue to say where the problem lies. If there is a product bug then in most cases you will be asked to test on the latest Cypress version or Cypress plugin version to confirm that it is not a problem which is already solved.

Considering that your error is not being able to find an element and the URL https://calm-sea-0e6f37a10-139.centralus.3.azurestaticapps.net/ continues to show a blank page when I view it, you may want to check whether it is displaying the content that you expect.

**Comment by fabu1985** [comment]
> @fabu1985
> 
> > Ok, entendido. Mi pregunta es ¿por qué crees que el problema es del preprocesador de pepino?
> 
> No hay suficiente información disponible sobre este problema para determinar dónde se encuentra. Si hay un error en el producto, en la mayoría de los casos se le solicitará que realice una prueba en la última versión de Cypress o en la versión del complemento de Cypress para confirmar que no se trata de un problema que ya se haya solucionado.
> 
> Teniendo en cuenta que tu error es no poder encontrar un elemento y la URL https://calm-sea-0e6f37a10-139.centralus.3.azurestaticapps.net/ sigue mostrando una página en blanco cuando la veo, es posible que quieras verificar si está mostrando el contenido que esperas.

@MikeMcC399  just in case, can you try to open the site in chrome, please? I'm almost sure you're using a different browser than Chrome, right? For rome developed reason the site worked ok in chrome, chromium, electron. but not for another browser.That's why I make sure that when running the githubactions I use the chrome browser

**Comment by MikeMcC399** [comment]
> @MikeMcC399 just in case, can you try to open the site in chrome, please? 

As I wrote in https://github.com/cypress-io/cypress/issues/30183#issuecomment-2331200244, I am using Google Chrome. Currently I have Version 128.0.6613.120 (Official Build) (64-bit) installed.

**Comment by fabu1985** [comment]
> > @MikeMcC399 just in case, can you try to open the site in chrome, please?
> 
> As I wrote in [#30183 (comment)](https://github.com/cypress-io/cypress/issues/30183#issuecomment-2331200244), I am using Google Chrome. Currently I have Version 128.0.6613.120 (Official Build) (64-bit) installed.

So, let me tell u that I replaced the "cypress-cucumber-preprocessor": "^4.3.1" by @badeball/cypress-cucumber-preprocessor, as you suggested me. Also, I increase the timeout...and still not working:


![image](https://github.com/user-attachments/assets/3bb4eb18-23cc-4462-a1a4-3eb036123407)

the tests agaisnt the azure static page failt.

**Comment by MikeMcC399** [comment]
@fabu1985

Please consider the original https://github.com/cypress-io/cypress/issues/30183#issuecomment-2329402611 from the Cypress.io team:

> There's not much for us to look into on our side for this. This element is not being found for some reason. [Test Replay](https://docs.cypress.io/guides/cloud/test-replay) is a good way to debug failures in CI as it replays entirely what happened where you can visually see it.
