### ISSUE TITLE
Massive memory leak (Aw snap) when using custom chai assertions

### ISSUE THREAD

**Issue by lukeapage** [cypress-io/cypress#3046]
# Problem
If you use a custom chai library or assertion then there is a big memory leak when re-running (e.g. editing the spec file or clicking re-run). The end result is that when your writing tests, after 6-7 edits, the page crashes with a Aw-Snap. This may explain some of the Aw-Snap complaints where setting numRumsKeptInMemory to 0 doesn't help.

# Investigation
It took 10 hours of investigation before I hit upon the problem, because the devtools don't make it very clear and theres lots of links left in, so I ended up hacking in dispose methods into the cypress_runner file and slowly narrowing down the real retaining object that was causing everything to be kept.

If you use a custom chai library as per your example here:
https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/extending-cypress__chai-assertions/cypress/support

I believe that chai is globally created inside cypress_runner. When you use chai.use, it keeps a reference to the script you import. Because that script comes from another window context it keeps the reference to the spec runner window, which includes links to the last content window.

Removing our custom chai assertions changes the retained memory between re-runs from 180mb per run to 4mb.

I am not sure how to solve it - the chai code is static:
https://github.com/chaijs/chai/blob/26c8a794ec6da695f004bdbd6362a466dc3d098f/lib/chai.js#L37

Probably the best way would be to move the chai initialisation into the spec runner iframe, so it is imported each time the spec runner is created. Otherwise you'd have to refactor chai.

**Comment by lukeapage** [comment]
There is a work-around - it seems the memory leak is only in the `used` array that chai keeps internally.

If you add a chai assertion library manually e.g.

```
chaiSubset(chai, chai.util);
// instead of
// chai.use(chaiSubset);
```
then there is no leak.

**Comment by jennifer-shehane** [comment]
Would it be helpful to [open an issue within chai](https://github.com/chaijs/chai/issues)? They're pretty responsive about opened issues.

**Comment by lukeapage** [comment]
No, it is not an issue in chai, it’s an issue with how cypress uses chai. You need to decide how this should be fixed.. it may require work in chai to clear internal state, but it’s not a chai bug

**Comment by jennifer-shehane** [comment]
I have been *completely* unable to reproduce this in Cypress 3.3.1. I am running the exact example given from cypress-io/cypress-example-recipes:examples/extending-cypress__chai-assertions, I even did a loop to run same tests 200 times in one run. No change. `cypress open` and `cypress run` run fine, did rerunning, did editing the file. No changes.

Closing as not enough info. Please provide an exact reproducible example of what you are running to cause this and we will consider reopening.

**Comment by lukeapage** [comment]
@jennifer-shehane I've explained very clearly the code that is a memory leak and anyone digging into that code can see it is a potential problem when using chai extensions.

It is not causing you a problem because even though you run 200 times, I am guessing you do not have a large amount of css/javascript/dom running on the page. e.g. 200x10kb and 200x50mb are very different.

On the other hand this is not a core issue with cypress - its a colision between the way cypress works and the way chai is setup. If I worked for cypress I would just change your documentation to document the work-around.

**Comment by lukeapage** [comment]
Just closing an issue where I have carefully tried to help you and fellow cypress users (whilst hundreds of sloppy bug reports are still open) does not encourage me to be helpful in the future.

**Comment by jennifer-shehane** [comment]
@lukeapage I'm sorry for the frustration.	

I've taken another look at this. I imported both the `chai-date-string` and `chai-colors` within our most complex application, calling into the `chai.use` like in the example and still do not encounter any crashing or memory leaks. 

If there is a specific case that reproduces the error (large amount of css, js, etc) - we will need to know the case before diving in further. 

Every bugfix in Cypress has an accompanying test around it to ensure it has fixed the bug intended. So, while identifying a piece of code is part of delivering the fix - the other piece is having a reproducible failing test before we change the piece of code and a passing test after we change the piece of code. We, as a team, have to be able to reproduce the problem you are seeing and narrow down the smallest piece of code that causes it.
