### ISSUE TITLE
Some tests flake only if test runner's browser loses focus (or run headlessly)

### ISSUE THREAD

**Issue by blunderdome** [cypress-io/cypress#5023]
### Current behavior:

We have a number of tests which:

- Always pass when run in Chrome 76 with the browser in focus the whole time
- Always pass when run in Electron 61 with the browser in focus the whole time
- Often fail when run in Chrome 76 without the browser in focus
- Often fail when run in Electron 61 without the browser in focus
- Often fail when run headless

### Desired behavior:

Browser does not need to stay in focus; tests also pass headlessly.

### Steps to reproduce: (app code and test code)

```
it('is just an example', function () {
  cy.visit('https://noredink.com/logout')
  cy.contains('Log In').click()
  cy.findField('Email or username').type('example_user')
  cy.findField('Password').type('easypassword')
  cy.contains('button', 'Log in').click()
})
```

Here is a simple case - logging into our production app. This passes if you keep the browser in focus but sometimes fails if it loses focus (or is run headlessly):

![image](https://user-images.githubusercontent.com/4333625/63533030-fb070780-c4d9-11e9-9198-57918305a87e.png)

[Video: in focus and passing](https://recordit.co/lg6J85tKx8)

[Video: out of focus and failing](https://recordit.co/Tvm8z2LwQj)

We have other examples but they involve the admin side of our site and we probably shouldn't share them here. If you need more examples, let me know and we'll try to find something else that's appropriate to share.

### Versions

Cypress: 3.4.1
OS: macOS Mojave 10.14.5
Browser(s): Chrome 76 and Electron 61

### Other

https://github.com/cypress-io/cypress/issues/1892 may be relevant.

**Comment by vesper8** [comment]
not sure if related but I am also noticing that tests seem to randomly fail when running headless but run perfectly and consistently when run with the --headed flag. And it's not the same tests that randomly fail, it's quite random, but only happens when running headless.

not to mention that tests complete slower (sometimes MUCH slower) when running headless

**Comment by Bkucera** [comment]
@blunderdome I think your `findField` must be sensitive to window focus, and that's the reason your test fails. Is that command from https://github.com/testing-library/cypress-testing-library ? using the code @jennifer-shehane wrote, and see if the issue goes away.

**Comment by fr0** [comment]
I am experiencing something like this related to the `focusout` event. If the browser window has focus while the test is running, it passes. Otherwise, it fails.

Specifically, I have a popup that is hidden when it loses focus (when it receives `focusout`). Is there a known workaround for this?

**Comment by Bkucera** [comment]
@fr0 this should have been fixed in 3.4.1, could you give a reproducible?

**Comment by fr0** [comment]
> @fr0 this should have been fixed in 3.4.1, could you give a reproducible?

Sure, here you go:  https://github.com/fr0/cypress-focus-test

**Comment by ginna-baker** [comment]
This is a big issue for us testing our accessibility features, particular the "Skip to Main Content" feature in which the button is only visible on focus.

**Comment by Bkucera** [comment]
I have this in my backlog, thanks for the reproducible @fr0

**Comment by jennifer-shehane** [comment]
Another example, this UI also seems to have some logic listening to some sort of 'focus' event. 

![](http://g.recordit.co/uFAGqgLoY2.gif)

failing spec:

```js
it("Navigates to help article with mobile header menu", () => {
  cy.viewport("iphone-x");
  cy.visit("https://help.doterra.com/");
  cy.get('[data-aura-class="cHC_StartingCategories"]', { timeout: 25000 });
  cy.get('[data-aura-class="cDT_HeaderMobileMenu"]')
    .click();
  cy.get('.dtds-chevron-arrow-right[data-value="section-Help Mobile"]')
    .click();
  // this assertion fails if the window is not focused
  cy.get('.mobile-menu-carousel').should('be.visible')
});
```

**Comment by bodazhao** [comment]
Same issue here with the `.click()` method, only the error message is different and this problem doesn't exist with Electron 78

## Behaviour



## Steps to reproduce

[Codesandbox link](https://codesandbox.io/s/cypress-test-fails-when-not-in-focus-lu86t) with simplified source code

```js
// Cypress test
describe("Cypress fails when not in focus", () => {
  it("Try to click on the modal text button", () => {
	// deployed from codesandbox
    cy.visit("https://csb-lu86t-40qtfxquh.now.sh/");

    // gives us time to minimize (de-focus) the Cypress window
    cy.wait(5000);

    cy.get("[data-cy=show-modal]").click();
    cy.get("[data-cy=modal-text]").click();
  });
});
```

Error message (only with Chrome 80 not in focus)

```
CypressError: Timed out retrying: cy.click() failed because this element is not
visible:

<button data-cy="modal-text">i used ...</button>

This element '<button>' is not visible because its ancestor has 'position: fixed'
CSS property and it is overflowed by other elements. How about scrolling to the
element with cy.scrollIntoView()?

Fix this problem, or use {force: true} to disable error checking.

https://on.cypress.io/element-cannot-be-interacted-with
```

**Versions**
Cypress: 3.8.2
OS: macOS Catalina 10.15.4
Browser(s): Chrome 80 and Electron 78

**Comment by einfallstoll** [comment]
@bodazhao I have one test case which often fails in CI/headless with the same setup as you do:

- Select element, click it to show modal
- Select element within modal, click it
- Error, because it's invisible

**Comment by juanvillegas** [comment]
Is there any way to approach this? We are having issues with native checkboxes, if the window doesn't have focus the checkboxes aren't found by the cy.get() command.

**Comment by cmraible** [comment]
I've been experiencing similar "flakiness" in my tests, only when the window is in the background or minimized. The tests that fail all assert on visibility or click elements like Modals or Dropdowns, and they fail with an error stating that the element has opacity set to 0 (and thus is not visible). This seems to jive with the other examples in the thread, which all seem to be Modals/Dropdowns or similar.

From [Mozilla](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame):
> requestAnimationFrame() calls are paused in most browsers when running in background tabs or hidden <iframe>s in order to improve performance and battery life.

Note that the Cypress test runner embeds the application being tested in an iframe, so the above optimization would apply here.

I suspect that Chrome is pausing/throttling calls to requestAnimationFrame() when the Cypress window is backgrounded/minimized/occluded, and thus not rendering these items. 

I'm sorry that I don't have a solution for this, but I'm pretty confident this is at least one of the causes. Chrome also throttles JS timers in background tabs, but there is a flag to disable this, which I tried, but didn't see any improvement.

**A note on reproducibility**: Chromium just introduced occlusion tracking on Windows for Chrome 87, but has supported it for some time on macOS and some other operating systems. This may cause the iframe on Windows to still be considered "visible" even if it was covered by another window. This may be why @jennifer-shehane couldn't reproduce this in August 2019, assuming she was using a Windows machine. I don't have a windows machine to test, but theoretically you could reproduce by opening a new tab in the test runner to force the runner to the background.

**Comment by jennifer-shehane** [comment]
- I can't reproduce this example in Chrome 87 on any version of Cypress: https://github.com/cypress-io/cypress/issues/5023#issuecomment-606852354
- I was never able to reproduce this example: https://github.com/cypress-io/cypress/issues/5023#issue-484112201

I have a PR open to disable backgrounding occluded windows in Chrome. This could fix some of these issues for Chrome that people are encountering: https://github.com/cypress-io/cypress/pull/9640 

- This is reproducible in 6.1.0 and is not fixed by occluded PR: https://github.com/cypress-io/cypress/issues/5023#issuecomment-602523534
- This is reproducible in 6.1.0 and is not fixed by occluded PR: https://github.com/fr0/cypress-focus-test
- 
As for the comment on `requestAnimationFrame`, I'd have to research that more.

**Comment by cmraible** [comment]
@jennifer-shehane thanks for the prompt response. I put together a little test [repo](https://github.com/cmraible/cypress-rAF) to:

A) reproduce the failure reliably (on my machine at least)
B) confirm that requestAnimationFrame() is being throttled/paused altogether within Cypress

Instructions to reproduce and demonstrate the requestAnimationFrame() throttling are in the README.

The `--disable-backgrounding-occluded-windows` flag sounds promising -- maybe that will fix this? Not sure how/if I can test this myself...

Thanks again for all that you do, Cypress is dope 👍

**Comment by cmraible** [comment]
Chiming in: 6.2.1 fixed this completely for me

Thanks @jennifer-shehane and team

**Comment by adamalton** [comment]
I've just upgraded to 6.3.0, but unfortunately that didn't fix it for me.

My use case essentially boils down to:

```javascript
document.addEventListener('keydown', function (event) {
    if (document.querySelector('[data-some-specific-selector]:focus') && event.code === 'Space') {
        doSomething();
    }
});
```

With a Cypress test which does:

```javascript
cy.get('[data-some-specific-selector]').focus().type(' ');
// Some kind of assertion to check that doSomething was called
```

And it runs fine when Cypress stays in the foreground, but if I switch to another application while the test is running then `doSomething` is never called. When Cypress is run headless it seems to be intermittent.

I hope that's useful. Thank you for looking at this, I appreciate the effort being put into tackling this issue.

**Comment by manueledones** [comment]
I'm on cypress 7.1.0, Electron 89, I'm doing a `cy.contains('String').click();`  if the electron window has focus it works perfectly, but if it hasn't (i.g I'm focusing my IDE) it doesn't click, no error is logged

Here is the div i'm clicking on:
`<div _ngcontent-txt-c47="" tabindex="-1" class="suggestion ng-star-inserted" ng-reflect-ng-class="[object Object]"> String </div>`

I'll try to understand what's the problem here, maybe the tabindex = "-1" ? Idk...

**Comment by jennifer-shehane** [comment]
We should look at what CDP does when you set "Emulate a focused page" - this seems to have fixed some of our internal issues with focus. 
<img width="517" alt="Screen Shot 2021-10-13 at 3 00 39 PM" src="https://user-images.githubusercontent.com/1271364/137204468-aa90ea6a-3777-4321-a6a5-24adb3287cff.png">

**Comment by nyghtly-derek** [comment]
I've encountered a similar problem while testing an Angular JS application:

`npx cypress open` (with focus) -- pass
`npx cypress open` (without focus) -- *fail*
`npx cypress run` -- pass

**Comment by Mayank-jain34** [comment]
Hi Team, is there any update on this. We are also running into the same issue. Thanks!

**Comment by charleshimmer** [comment]
@nyghtly-derek similar issue for but with React app. We are finding focus is lose causing the app to be in an incorrect state if focus is on another app other than the cypress browser. Running headless doesn't seem to have this issue.
