### ISSUE TITLE
cy.setCookie is Not Setting Desired Cookie Expiry

### ISSUE THREAD

**Issue by ghost** [cypress-io/cypress#5599]
### Current behavior:

`cy.setCookie` is not setting the `expiry` as desired.

### Desired behavior:

`cy.setCookie` sets the `expiry` that the code provides.

### Steps to reproduce:

```js
describe('Cypress Cookie Issue', function () {
    it('Expiry Problem', function () {
        let email = 'fake@qa.com'
        let password = 'abc123'
        cy.createAccount(email, password)
        cy.login(email, password)
        cy.visit('/')
        cy.getCookie('jwt').then((jwt) => {
            cy.setCookie('jwt', jwt.value, {expiry: 10000000000})
            cy.getCookie('jwt').then((setJWT) => {
                expect(setJWT.expiry).to.equal(10000000000)
            })
        })
    })
})
```
![image](https://user-images.githubusercontent.com/57365666/68147579-54db7300-ff08-11e9-9bec-1bfa8de6c2a6.png)

### Versions

Cypress 3.6.0, Chrome 78.

I started experiencing this problem when I upgraded from Cypress 3.2.0 to 3.6.0.

**Comment by jennifer-shehane** [comment]
Hey @toddmkemp, simplifying this test - it does set a cookies expiry and overwrites an existing set when the cookie is set on the same domain here. 

```js
it('Expiry Problem', function () {
  cy.visit('https://example.cypress.io/commands/traversal')
  cy.setCookie('foo', 'bar', { expiry: 50000000 })
  cy.getCookie('foo').then((jwt) => {
    cy.setCookie('foo', 'bar', { expiry: 10000000000 })
    cy.getCookie('foo').then((foo) => {
      expect(foo.expiry).to.equal(10000000000)
    })
  })
})
```

We'll need a more specific example of the issue that we can run on our computer exhibiting the exact issue before we can move forward.

**Comment by toddmkemp** [comment]
Hi,

I've investigated a little more and the issue is a little more complex than what I initially thought.  Using a similar approach to cookie manipulation that you took, I wrote the following:

```
describe('Cypress Cookie Issue', function () {

    beforeEach(function () {
        cy.visit('https://en.wikipedia.org/')
    })

    it('Passes', function () {
        cy.getCookie('WMF-Last-Access-Global')
        cy.setCookie('WMF-Last-Access-Global', 'value', {expiry: 10000000000})
        cy.getCookie('WMF-Last-Access-Global').then((cookie) => {
            expect(cookie.expiry).to.equal(10000000000)
        })
    })

    it('Fails', function () {
        cy.getCookie('WMF-Last-Access')
        cy.setCookie('WMF-Last-Access', 'value', {expiry: 10000000000})
        cy.getCookie('WMF-Last-Access').then((cookie) => {
            expect(cookie.expiry).to.equal(10000000000)
        })
    })
})
```

The first test passes and the second one fails.  The only difference between the tests is the cookie itself.  Specifically, the domains of the cookies are different which seems to be what is problematic here.

Please let me know if you have questions or if there is anything else I can provide to help you diagnose the issue.

**Comment by toddmkemp** [comment]
@jennifer-shehane : Did my latest comments provide any clarity on the matter?  I'm happy to continue to investigate if you are still unable to reproduce the problem.

**Comment by toddmkemp** [comment]
Hello again @jennifer-shehane. I saw in the release notes for Cypress versions since 3.6.0 that there have been a number of fixes for behaviour involving cookies so I upgraded to version 3.8.1 to see if that would fix this issue but I am still seeing the failure here.

![image](https://user-images.githubusercontent.com/57365666/71626139-a8d99f80-2bb9-11ea-8431-087ab956be1d.png)

Again, the only difference between these tests is the cookie itself, so I would expect both tests to pass.

Please provide an update on this issue.

**Comment by jennifer-shehane** [comment]
@toddmkemp I have confirmed the behavior you're explaining. There are a couple of other differences in the cookies, mainly one is `secure: true` and `httpOnly: true` while the other is `false` on both of these attributes. 

```js

it('Passes', function () {
  cy.visit('https://en.wikipedia.org/')
  cy.setCookie('WMF-Last-Access-Global', 'value', { expiry: 10000000000 })
  cy.getCookie('WMF-Last-Access-Global').then((cookie) => {
    expect(cookie.httpOnly).to.be.false
    expect(cookie.secure).to.be.false
    expect(cookie.domain).to.eq('.wikipedia.org')
    expect(cookie.expiry).to.equal(10000000000)
  })
})

it('Fails', function () {
  cy.visit('https://en.wikipedia.org/')
  cy.setCookie('WMF-Last-Access', 'value', { expiry: 10000000000 })
  cy.getCookie('WMF-Last-Access').then((cookie) => {
    expect(cookie.httpOnly).to.be.true
    expect(cookie.secure).to.be.true
    expect(cookie.domain).to.eq('en.wikipedia.org')
    expect(cookie.expiry).to.equal(10000000000) // fails here <---
  })
})
```

<img width="498" alt="Screen Shot 2020-01-02 at 12 53 11 PM" src="https://user-images.githubusercontent.com/1271364/71654200-dca1fa00-2d5e-11ea-9e8e-8cf8fb002c30.png">

**Comment by toddmkemp** [comment]
Hello again @jennifer-shehane .  Thanks for investigating; glad to hear you were able to reproduce the problem.  I hope that we will see this issue fixed in the near future! :)

**Comment by jennifer-shehane** [comment]
This is still an issue in 9.5.3

**Comment by emilyrohrbough** [comment]
related to: https://github.com/cypress-io/cypress/issues/20588

**Comment by slieschke** [comment]
The `setCookie()` expiry is still broken on the latest version of Cypress (v12.12.0 as of writing):

```javascript
it('Fails', function () {
  cy.visit('https://en.wikipedia.org/')
  cy.setCookie('WMF-Last-Access', 'value', { expiry: 10000000000 })
  cy.getCookie('WMF-Last-Access').then((cookie) => {
    expect(cookie.httpOnly).to.be.true
    expect(cookie.secure).to.be.true
    expect(cookie.domain).to.eq('en.wikipedia.org')
    expect(cookie.expiry).to.equal(10000000000)
  })
})
```

![CleanShot 2023-05-23 at 12 20 37](https://github.com/cypress-io/cypress/assets/742941/28262883-de76-401f-9836-6b6975dc6909)

**Comment by slieschke** [comment]
This is still failing with the latest version of Cypress (v13.15.1 as of writing).
```javascript
it('Fails', function () {
  cy.log(`Cypress version: ${Cypress.version}`)
  cy.visit('https://en.wikipedia.org/')
  cy.setCookie('WMF-Last-Access', 'value', { expiry: 10000000000 })
  cy.getCookie('WMF-Last-Access').then((cookie) => {
    expect(cookie.httpOnly).to.be.true
    expect(cookie.secure).to.be.true
    expect(cookie.domain).to.eq('en.wikipedia.org')
    expect(cookie.expiry).to.equal(10000000000)
  })
})
```
![CleanShot 2024-10-31 at 23 30 23@2x](https://github.com/user-attachments/assets/142019ec-9f34-4260-80ba-4964e28302c8)
