### ISSUE TITLE
Cypress hangs on CI

### ISSUE THREAD

**Issue by valdasgra** [cypress-io/cypress#5645]
I was using cypress 3.4 on the Azure pipeline and it was working fine. The problem started when I upgraded the cypress version to 3.5. The cypress run hangs on the first test suite and doesn't move forward. 
I upgraded the cypress version to 3.6 and it was the same.
I am using junit for test reporter and have nothing else special.
Also the cypress test runs fine on my local without any problem.

```json
{
  "reporter": "junit",
  "viewportHeight": 1600,
  "viewportWidth": 1080,
  "reporterOptions": {
    "mochaFile": "./cypress/test-output-[hash].xml",
    "toConsole": true,
    "attachments": true
  },
  "video": false,
  "env": {
    "urlEnv": "staging"
  },
  "chromeWebSecurity": false,
  "pageLoadTimeout": 50000
}
```
The test suites are quite simple - just a combination of `cy.visit` and `cy.get.type`.

**Comment by dlabrecque** [comment]
Hi,
Same here using 3.6.0 with TeamCity.
I thought maybe video compression was causing an issue so I changed it to false, but it still hangs about once in 3-4 times. I manually have to cancel the run when it happens.
I added `DEBUG=cypress:*` and attached 2 logs. 1 where it hangs and 1 where it doesn't.
It seems to attempt to close the browser, but it doesn't close properly for some reason.

[teamcity_cypress_debug_HANG.log.zip](https://github.com/cypress-io/cypress/files/3825922/teamcity_cypress_debug_HANG.log.zip)
[teamcity_cypress_debug_OK.log.zip](https://github.com/cypress-io/cypress/files/3825923/teamcity_cypress_debug_OK.log.zip)

**Comment by harvitronix** [comment]
I'm having the same problem. 3.4.1 works fine. 3.5.0 and 3.6.1 both hang after starting a test, but not consistently. The log just shows a `deleteCookies()` call.

**Comment by cooleiwhistles** [comment]
Having the same problem in 3.6.1 in Jenkins using docker image. Any given spec will hang at random, but the suite works fine in 3.4.1.

**Comment by fdaryaee** [comment]
Having the same problem with 3.5.0 and 3.6.1, octopus jobs hangs on the very first spec. It works well with 3.4.1.

**Comment by jennifer-shehane** [comment]
Hey everyone, can you verify what operating system Cypress is hanging on?

Also, capturing and printing the entire set of DEBUG logs may be helpful. [Instructions here](https://on.cypress.io/debugging#Debug-the-Command-Line)

**Comment by grantspeelman** [comment]
Not sure if this is helpful, but our freezing on CircleCI went away when adding "-b chrome" to the run command.

**Comment by grantspeelman** [comment]
Managed to run the same set of tests locally in run mode and they freeze the same like on CircleCI.
* locally run macos
* circleci is linux docker

Here is a link to log files:
https://gist.github.com/grantspeelman/2e858d78100245fcaa92a8827c0630d8

**Comment by harvitronix** [comment]
@jennifer-shehane This is happening to me on Ubuntu 18.04.

**Comment by mduft** [comment]
Same here, working tests with 3.4.1, with 3.6.1 cypress stops at some point and hangs...

**Comment by dwelle** [comment]
Possibly related to https://github.com/cypress-io/cypress/issues/5475?

**Comment by selangley-wa** [comment]
Having this issue on Azure Dev Ops.  My very simple spec is not using any history.

**Comment by selangley-wa** [comment]
From what I read in #5558, it might work using Chrome instead of Electron.  Anyone try that? 

I attempted to build a version of Cypress from source from a date intermediate between the 3.4.1 and the 3.5.0 releases in order to figure out what commit broke it.  But I was unsuccessful in building Cypress from source (on Windows 10) - lots of errors that I couldn't solve related to dependent packages.

**Comment by 9odzilla** [comment]
Having the same Issue. Tests team fine on version 3.4.1 but are hanging on the first test on version 3.6.1. using Chrome 78.

**Comment by milandebuck** [comment]
Having the same issue on Azure Devops Build Agent(Windows 10) Cypress version 3.6.1

**Comment by EugeneCh** [comment]
Confirm hanging on Azure Devops Build Agent Cypress version 3.7.0 (electron 73)

Downgrade to cypress 3.4.1 (electron 61) fixed such problem.

**Comment by ttomaszewski** [comment]
I'm seeing hanging in CI as well. Will just intermittently fail at a start of another spec file. Not always the same spec file. I downgraded to 3.4.1 but saw the issue there too. When running with `DEBUG=cypress*` I see it gets hung up at a proxy after a `cy.request` and the returned response.

**Comment by 9odzilla** [comment]
Just a suggestion, but someone posted in closed issue [#5190](https://github.com/cypress-io/cypress/issues/5190) passing Chrome arguments prior to execution. I tried this and was able to fix my issues. I determined that pushing '--disable-dev-shm-usage' as a chrome option solved my hanging issue in pipeline execution. Perhaps you guys could try this as well. I am able to now execute all tests using either Chrome or Electron in 3.7 without any hiccups.

**Comment by mduft** [comment]
I tried again to upgrade from 3.4.1 and it still hangs on 3.7.0. This time I took some time to investigate and also tried `--disable-dev-shm-usage` (unfortunately did not help).

It hangs /only/ in headless mode, and hangs on any `cy.screenshot()` call - seemingly forever. When running using cypress open, all our specs run fine without any problem now (which also was not the case for 3.5.x and 3.6.x).

From debug logs I can see this:

```
2019-12-11T13:44:50.951Z cypress:server:screenshot (s86) capture and check { tries: 1, totalDuration: 0 }
2019-12-11T13:44:50.951Z cypress:server:browsers:electron debugger: sending Page.captureScreenshot with params undefined
2019-12-11T13:45:14.249Z cypress:https-proxy received error on client browserSocket { err: { Error: write EPIPE at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:82:16) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }, url: 'localhost:36247' }
2019-12-11T13:45:14.249Z cypress:https-proxy received error on client browserSocket { err: { Error: write EPIPE at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:82:16) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }, url: 'localhost:36247' }
2019-12-11T13:45:14.249Z cypress:https-proxy received error on client browserSocket { err: { Error: write EPIPE at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:82:16) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }, url: 'localhost:36247' }
2019-12-11T13:45:17.134Z cypress:https-proxy received error on client browserSocket { err: { Error: write EPIPE at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:82:16) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }, url: 'localhost:44769' }
2019-12-11T13:45:17.134Z cypress:https-proxy received error on client browserSocket { err: { Error: write EPIPE at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:82:16) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }, url: 'localhost:44769' }
2019-12-11T13:45:17.134Z cypress:https-proxy received error on client browserSocket { err: { Error: write EPIPE at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:82:16) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }, url: 'localhost:44769' }
2019-12-11T13:45:22.922Z cypress:https-proxy received error on client browserSocket { err: { Error: write EPIPE at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:82:16) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }, url: 'localhost:36247' }
2019-12-11T13:45:22.923Z cypress:https-proxy received error on client browserSocket { err: { Error: write EPIPE at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:82:16) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }, url: 'localhost:36247' }
2019-12-11T13:45:22.923Z cypress:https-proxy received error on client browserSocket { err: { Error: write EPIPE at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:82:16) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }, url: 'localhost:36247' }
2019-12-11T13:45:22.923Z cypress:https-proxy received error on client browserSocket { err: { Error: write EPIPE at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:82:16) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }, url: 'localhost:36247' }
2019-12-11T13:45:22.924Z cypress:https-proxy received error on client browserSocket { err: { Error: write EPIPE at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:82:16) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }, url: 'localhost:36247' }
2019-12-11T13:45:31.913Z cypress:https-proxy received error on client browserSocket { err: { Error: write EPIPE at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:82:16) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }, url: 'localhost:44769' }
2019-12-11T13:45:31.913Z cypress:https-proxy received error on client browserSocket { err: { Error: write EPIPE at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:82:16) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }, url: 'localhost:44769' }
2019-12-11T13:45:31.914Z cypress:https-proxy received error on client browserSocket { err: { Error: write EPIPE at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:82:16) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }, url: 'localhost:44769' }
2019-12-11T13:45:31.914Z cypress:https-proxy received error on client browserSocket { err: { Error: write EPIPE at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:82:16) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }, url: 'localhost:44769' }
2019-12-11T13:45:31.914Z cypress:https-proxy received error on client browserSocket { err: { Error: write EPIPE at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:82:16) errno: 'EPIPE', code: 'EPIPE', syscall: 'write' }, url: 'localhost:44769' }
```

**Comment by ttomaszewski** [comment]
@9odzilla Thanks. I tried `--disable-dev-shm-usage` but unfortunately that did not help either. Thought it did but after a few test runs I saw the issue again.

**Comment by mduft** [comment]
Retested all this with 3.8.0. It works now. All hangs, performance degradation, etc. seem to be gone, and headed & headless Electron work fine again.

**Comment by jennifer-shehane** [comment]
Can everyone try updating to our latest [Cypress 3.8.0 version](https://on.cypress.io/changelog#3-8-0) and let us know the results? We fixed a lot of regressions introduced in 3.5.0 and are unaware of any leftover involving CI hanging, so that would be really appreciated.

**Comment by jennifer-shehane** [comment]
@valdasgra @dlabrecque @harvitronix @cooleiwhistles @fdaryaee @selangley-wa @9odzilla @milandebuck @EugeneCh 

Can everyone try updating to our latest [Cypress 3.8.0 version](https://on.cypress.io/changelog#3-8-0) and let us know the results? We fixed a lot of regressions introduced in 3.5.0 and are unaware of any leftover involving CI hanging, so that would be really appreciated.

**Comment by 9odzilla** [comment]
I have upgraded to 3.8.0 and now I randomly get the following error in different tests:

```
Out of memory. size=4284416
We detected that the Chromium Renderer process just crashed.
```

I believe 3.7 was not giving me an issue. Executing in docker/azure pipeline using electron.

**Comment by 9odzilla** [comment]
I've added "--ip=host" to my docker container and it is now working without issue.

**Comment by harvitronix** [comment]
@jennifer-shehane Confirmed upgrading to 3.8.0 solved the random hanging issue for me. Thanks!

**Comment by 9odzilla** [comment]
> I've added "--ip=host" to my docker container and it is now working without issue.

This apparently did not fix my issue. It's no longer hanging, but I am getting the renderer just crashed error randomly now.

**Comment by DLatheron** [comment]
We have the same problem on ubuntu, under Jenkins... upgrading to 3.8.0 did NOT fix the issue... reverted to 3.4.1 seems to.

**Comment by dlabrecque** [comment]
Not hanging so far on 3.8.0. Thank you for all the effort put into this.

**Comment by ngbrown** [comment]
For me, the Cypress process on Azure DevOps CI builds (using own Windows Server instance) was working on 3.4.1 would hang after finishing the tests in 3.5, 3.6, and 3.7.  It now works on 3.8.  Thanks.

**Comment by ttomaszewski** [comment]
I thought upgrading to 3.8 did the trick, but I'm seeing the randomly hanging again in Jenkins running docker.

**Comment by ttomaszewski** [comment]
Ran in Jenkins/Docker with DEBUG mode using newest version 3.8.1. This is an error i noticed. 

```
2020-01-02T20:44:37.699Z cypress-verbose:server:video:frames video stream drained
2020-01-02T20:44:37.716Z cypress:proxy:http Entering stage { stage: 'IncomingRequest' }
2020-01-02T20:44:37.716Z cypress:proxy:http Running middleware { stage: 'IncomingRequest', middlewareName: 'LogRequest' }
2020-01-02T20:44:37.716Z cypress:proxy:http:request-middleware proxying request { req: { method: 'HEAD', proxiedUrl: 'http://ubdwvtpxaejnpn/', headers: { host: 'ubdwvtpxaejnpn', 'proxy-connection': 'keep-alive', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36', 'accept-encoding': 'gzip, deflate' } } }
2020-01-02T20:44:37.716Z cypress:proxy:http Running middleware { stage: 'IncomingRequest', middlewareName: 'RedirectToClientRouteIfUnloaded' }
2020-01-02T20:44:37.716Z cypress:proxy:http Running middleware { stage: 'IncomingRequest', middlewareName: 'RedirectToClientRouteIfNotProxied' }
2020-01-02T20:44:37.716Z cypress:proxy:http Running middleware { stage: 'IncomingRequest', middlewareName: 'EndRequestsToBlacklistedHosts' }
2020-01-02T20:44:37.716Z cypress:proxy:http Running middleware { stage: 'IncomingRequest', middlewareName: 'MaybeEndRequestWithBufferedResponse' }
2020-01-02T20:44:37.717Z cypress:proxy:http Running middleware { stage: 'IncomingRequest', middlewareName: 'StripUnsupportedAcceptEncoding' }
2020-01-02T20:44:37.717Z cypress:proxy:http Running middleware { stage: 'IncomingRequest', middlewareName: 'MaybeSetBasicAuthHeaders' }
2020-01-02T20:44:37.717Z cypress:server:server Getting remote state: { auth: null, props: { port: '8080', tld: 'localhost', domain: '' }, origin: 'http://localhost:8080', strategy: 'http', visiting: false, domainName: 'localhost', fileServer: null }
2020-01-02T20:44:37.717Z cypress:proxy:http Running middleware { stage: 'IncomingRequest', middlewareName: 'SendRequestOutgoing' }
2020-01-02T20:44:37.717Z cypress:server:server Getting remote state: { auth: null, props: { port: '8080', tld: 'localhost', domain: '' }, origin: 'http://localhost:8080', strategy: 'http', visiting: false, domainName: 'localhost', fileServer: null }
2020-01-02T20:44:37.717Z cypress:network:agent addRequest called { isHttps: false, href: 'http://ubdwvtpxaejnpn/' }
2020-01-02T20:44:37.717Z cypress:network:connect beginning getAddress { hostname: 'ubdwvtpxaejnpn', port: 80 }
2020-01-02T20:44:37.718Z cypress:server:stream_buffer stream buffer writeable final called
2020-01-02T20:44:37.718Z cypress:proxy:http Entering stage { stage: 'IncomingRequest' }
2020-01-02T20:44:37.718Z cypress:proxy:http Running middleware { stage: 'IncomingRequest', middlewareName: 'LogRequest' }
2020-01-02T20:44:37.718Z cypress:proxy:http:request-middleware proxying request { req: { method: 'HEAD', proxiedUrl: 'http://pyjvrgazlffdzg/', headers: { host: 'pyjvrgazlffdzg', 'proxy-connection': 'keep-alive', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36', 'accept-encoding': 'gzip, deflate' } } }
2020-01-02T20:44:37.718Z cypress:proxy:http Running middleware { stage: 'IncomingRequest', middlewareName: 'RedirectToClientRouteIfUnloaded' }
2020-01-02T20:44:37.718Z cypress:proxy:http Running middleware { stage: 'IncomingRequest', middlewareName: 'RedirectToClientRouteIfNotProxied' }
2020-01-02T20:44:37.718Z cypress:proxy:http Running middleware { stage: 'IncomingRequest', middlewareName: 'EndRequestsToBlacklistedHosts' }
2020-01-02T20:44:37.718Z cypress:proxy:http Running middleware { stage: 'IncomingRequest', middlewareName: 'MaybeEndRequestWithBufferedResponse' }
2020-01-02T20:44:37.718Z cypress:proxy:http Running middleware { stage: 'IncomingRequest', middlewareName: 'StripUnsupportedAcceptEncoding' }
2020-01-02T20:44:37.718Z cypress:proxy:http Running middleware { stage: 'IncomingRequest', middlewareName: 'MaybeSetBasicAuthHeaders' }
2020-01-02T20:44:37.718Z cypress:server:server Getting remote state: { auth: null, props: { port: '8080', tld: 'localhost', domain: '' }, origin: 'http://localhost:8080', strategy: 'http', visiting: false, domainName: 'localhost', fileServer: null }
2020-01-02T20:44:37.718Z cypress:proxy:http Running middleware { stage: 'IncomingRequest', middlewareName: 'SendRequestOutgoing' }
2020-01-02T20:44:37.719Z cypress:server:server Getting remote state: { auth: null, props: { port: '8080', tld: 'localhost', domain: '' }, origin: 'http://localhost:8080', strategy: 'http', visiting: false, domainName: 'localhost', fileServer: null }
2020-01-02T20:44:37.719Z cypress:network:agent addRequest called { isHttps: false, href: 'http://pyjvrgazlffdzg/' }
2020-01-02T20:44:37.719Z cypress:network:connect beginning getAddress { hostname: 'pyjvrgazlffdzg', port: 80 }
2020-01-02T20:44:37.719Z cypress:server:stream_buffer stream buffer writeable final called
2020-01-02T20:44:37.720Z cypress:proxy:http Entering stage { stage: 'IncomingRequest' }
2020-01-02T20:44:37.720Z cypress:proxy:http Running middleware { stage: 'IncomingRequest', middlewareName: 'LogRequest' }
2020-01-02T20:44:37.720Z cypress:proxy:http:request-middleware proxying request { req: { method: 'HEAD', proxiedUrl: 'http://nwowdrxskon/', headers: { host: 'nwowdrxskon', 'proxy-connection': 'keep-alive', 'user-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36', 'accept-encoding': 'gzip, deflate' } } }
2020-01-02T20:44:37.720Z cypress:proxy:http Running middleware { stage: 'IncomingRequest', middlewareName: 'RedirectToClientRouteIfUnloaded' }
2020-01-02T20:44:37.720Z cypress:proxy:http Running middleware { stage: 'IncomingRequest', middlewareName: 'RedirectToClientRouteIfNotProxied' }
2020-01-02T20:44:37.720Z cypress:proxy:http Running middleware { stage: 'IncomingRequest', middlewareName: 'EndRequestsToBlacklistedHosts' }
2020-01-02T20:44:37.720Z cypress:proxy:http Running middleware { stage: 'IncomingRequest', middlewareName: 'MaybeEndRequestWithBufferedResponse' }
2020-01-02T20:44:37.720Z cypress:proxy:http Running middleware { stage: 'IncomingRequest', middlewareName: 'StripUnsupportedAcceptEncoding' }
2020-01-02T20:44:37.720Z cypress:proxy:http Running middleware { stage: 'IncomingRequest', middlewareName: 'MaybeSetBasicAuthHeaders' }
2020-01-02T20:44:37.720Z cypress:server:server Getting remote state: { auth: null, props: { port: '8080', tld: 'localhost', domain: '' }, origin: 'http://localhost:8080', strategy: 'http', visiting: false, domainName: 'localhost', fileServer: null }
2020-01-02T20:44:37.720Z cypress:proxy:http Running middleware { stage: 'IncomingRequest', middlewareName: 'SendRequestOutgoing' }
2020-01-02T20:44:37.720Z cypress:server:server Getting remote state: { auth: null, props: { port: '8080', tld: 'localhost', domain: '' }, origin: 'http://localhost:8080', strategy: 'http', visiting: false, domainName: 'localhost', fileServer: null }
2020-01-02T20:44:37.720Z cypress:network:agent addRequest called { isHttps: false, href: 'http://nwowdrxskon/' }
2020-01-02T20:44:37.720Z cypress:network:connect beginning getAddress { hostname: 'nwowdrxskon', port: 80 }
2020-01-02T20:44:37.721Z cypress:server:stream_buffer stream buffer writeable final called
2020-01-02T20:44:37.737Z cypress:network:connect error getting address {
  hostname: 'ubdwvtpxaejnpn',
  port: 80,
  err: OperationalError: getaddrinfo ENOTFOUND ubdwvtpxaejnpn
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (dns.js:72:26)
   {
    cause: Error: getaddrinfo ENOTFOUND ubdwvtpxaejnpn
        at GetAddrInfoReqWrap.onlookupall [as oncomplete] (dns.js:72:26)
     {
      errno: 'ENOTFOUND',
      code: 'ENOTFOUND',
      syscall: 'getaddrinfo',
      hostname: 'ubdwvtpxaejnpn'
    },
    isOperational: true,
    errno: 'ENOTFOUND',
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'ubdwvtpxaejnpn'
  }
}
2020-01-02T20:44:37.738Z cypress:network:agent got family { family: undefined, href: 'http://ubdwvtpxaejnpn/' }
2020-01-02T20:44:37.741Z cypress:network:connect error getting address {
  hostname: 'nwowdrxskon',
  port: 80,
  err: OperationalError: getaddrinfo ENOTFOUND nwowdrxskon
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (dns.js:72:26)
   {
    cause: Error: getaddrinfo ENOTFOUND nwowdrxskon
        at GetAddrInfoReqWrap.onlookupall [as oncomplete] (dns.js:72:26)
     {
      errno: 'ENOTFOUND',
      code: 'ENOTFOUND',
      syscall: 'getaddrinfo',
      hostname: 'nwowdrxskon'
    },
    isOperational: true,
    errno: 'ENOTFOUND',
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'nwowdrxskon'
  }
}
2020-01-02T20:44:37.741Z cypress:network:agent got family { family: undefined, href: 'http://nwowdrxskon/' }
2020-01-02T20:44:37.762Z cypress:server:request received an error making http request { timeout: 60000, retryIntervals: [ 0, 100, 200, 200 ], url: 'http://nwowdrxskon/', requestId: 'request528', retryOnNetworkFailure: true, retryOnStatusCodeFailure: false, delaysRemaining: [ 0, 100, 200, 200 ], err: Error: getaddrinfo ENOTFOUND nwowdrxskon at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) { errno: 'ENOTFOUND', code: 'ENOTFOUND', syscall: 'getaddrinfo', hostname: 'nwowdrxskon' } }
2020-01-02T20:44:37.762Z cypress:server:request retrying request { timeout: 60000, retryIntervals: [ 0, 100, 200, 200 ], url: 'http://nwowdrxskon/', requestId: 'request528', retryOnNetworkFailure: true, retryOnStatusCodeFailure: false, delaysRemaining: [ 100, 200, 200 ], delay: 0, attempt: 1 }
2020-01-02T20:44:37.763Z cypress:server:stream_buffer buffered stream EOF { readerId: 'reader529' }
2020-01-02T20:44:37.763Z cypress:network:agent addRequest called { isHttps: false, href: 'http://nwowdrxskon/' }
2020-01-02T20:44:37.763Z cypress:network:connect beginning getAddress { hostname: 'nwowdrxskon', port: 80 }
```
Any idea on the random hostnames?

**Comment by valdasgra** [comment]
@jennifer-shehane Upgraded the cypress version to 3.8.2 and it fixed the issue!
Thanks!

**Comment by jennifer-shehane** [comment]
This issue will be closed to further comment as the exact issue here was resolved and tested. 

If you're experiencing a bug similar to this in Cypress, please [open a new issue](https://github.com/cypress-io/cypress/issues/new) with a fully reproducible example that we can run. There may be a specific edge case with the issue that we need more detail to fix.
