### ISSUE TITLE
Cypress invalid proxy certificate affects disk cache

### ISSUE THREAD

**Issue by jsantha** [cypress-io/cypress#7307]
### Current behavior:

Information that certificate error is purely cosmetic problem as specified here [docs.cypress.io/faq/questions/using-cypress-faq.html](https://docs.cypress.io/faq/questions/using-cypress-faq.html#When-I-visit-my-site-directly-the-certificate-is-verified-however-the-browser-launched-through-Cypress-is-showing-it-as-%E2%80%9CNot-Secure%E2%80%9D-Why) is misleading. 

Chrome, as reported here [bugs.chromium.org/p/chromium/issues/detail?id=110649](https://bugs.chromium.org/p/chromium/issues/detail?id=110649#c8) ignores http caching when any error with ssl certificate occurs. This means that the application under the test is affected and not behaving as intended (http caching is fully disabled, app load time can be significantly slower...).

### Desired behavior:

1) Inform about this potential problem in FAQ
2) Maybe inform that this problem can be resolved by importing `CypressProxyCA` from `cy/production/proxy/certs/ca.pem` to the Trusted Root Certification Authority store

### Test code to reproduce

https://github.com/jsantha/cypress-invalid-cert

### Versions

Chrome from version ~16 to actual (81)
Windows 10
Cypress 4.5.0

**Comment by flotwig** [comment]
> This means that the application under the test is affected and not behaving as intended (http caching is fully disabled, app load time can be significantly slower...).

Have you been able to observe this behavior in Cypress? I have not noticed cache behaving oddly, but it's possible I have not been working on enough HTTPS stuff to see it. We do pass arguments to Chrome to force them to permit invalid certs, so it could also be affecting this behavior.

---

> Maybe inform that this problem can be resolved by importing `CypressProxyCA` from `cy/production/proxy/certs` to the Trusted Root Certification Authority store

Hmm, this would technically work, but some users will not want Cypress to touch their CA store. Also, this will probably break in any managed environment with antivirus/GPO setups that prevent malicious CAs being installed.

It would be a security issue too. Although the test runner's CA keys are not shared pubicly (they are generated locally per-computer and cached), it's possible that malware on a user's computer could read the CA file and use it to intercept HTTPS traffic without the user's knowledge (if Cypress were added to the CA store)

**Comment by jsantha** [comment]
> I ask because this comment seems to imply that caching DOES work, but it is in-memory, not written to disk.

Quick peek into chromium source code shows that this behavior is intended and cannot be prevented with browser arguments: [/net/http/http_cache_transaction.cc](https://github.com/chromium/chromium/blob/55f44515cd0b9e7739b434d1c62f4b7e321cd530/net/http/http_cache_transaction.cc#L3096)

Anyway, I have made a quick test:

Chrome 81
Windows 10
Cypress 4.5.0

1) invalid certificate = **no caching**

![image](https://user-images.githubusercontent.com/5988563/81989032-c83f0980-963c-11ea-9007-5a8a78575117.png)

2) trusted certificate = **caching works as expected**

![image](https://user-images.githubusercontent.com/5988563/81989268-3b488000-963d-11ea-9946-b69a6ff6b509.png)

Our application leverages http caching for some quite heavy REST API calls and since I have rewritten some of our e2e tests from Selenium to Cypress, I have immediately noticed that Cypress test cases runs much slower than those running via Selenium.

> It would be a security issue too. Although the test runner's CA keys are not shared pubicly (they are generated locally per-computer and cached), it's possible that malware on a user's computer could read the CA file and use it to intercept HTTPS traffic without the user's knowledge (if Cypress were added to the CA store)

I'm not really familiar with internal working of those certificates and theirs potential security issues but we could perhaps inspire at .NET Core SDK that provides a CLI option to make its own development certificate trusted [Trust the ASP.NET Core HTTPS development certificate on Windows and macOS](https://docs.microsoft.com/en-us/aspnet/core/security/enforcing-ssl?view=aspnetcore-3.1&tabs=visual-studio#trust-the-aspnet-core-https-development-certificate-on-windows-and-macos) and we could inform users about the potential security risks you mentioned.

**Comment by jennifer-shehane** [comment]
Can you provide the full repo/code for your reproduction of the caching issue?

I was not able to verify the behavior that caching is effected from within Cypress when SSL certificate errors are present. 

The cache *is* cleared in Cypress before each run of a spec file. So there will not be any caching on the first run of a test, but the subsequent runs of tests, resources should be cached. 

You can observe this with the following test:

```js
it('test', () => {
 cy.visit('https://reactjs.org/docs/getting-started.html')
});
 
it('test2', () => {
 cy.visit('https://reactjs.org/docs/getting-started.html')
});
```

When looking at the network tab (filtering by Img), the first test has the 'search.svg' with a 200 status. The second test, the request has the 'search.svg' return as status 304 Not Modified. It is returning with the cached image. 

<img width="609" alt="Screen Shot 2020-05-15 at 4 33 32 PM copy" src="https://user-images.githubusercontent.com/1271364/82038752-059da880-96ca-11ea-80b4-7a80c5350584.png">

**Comment by jsantha** [comment]
@jennifer-shehane You have chosen wrong file to check caching, the `search.svg` has `max-age=0` and utilizing etag - this request always hits the server but skips response download when etag matches (304). I created a disk cache scenario here https://github.com/jsantha/cypress-invalid-cert

**Comment by jennifer-shehane** [comment]
Yeah, it does seem that the invalid certificate will affect disk cache. Thanks for providing the repo.

We could maybe fix this by implementing the certificate override at the remote debugger protocol level (if [Chromium’s comment](https://github.com/chromium/chromium/blob/55f44515cd0b9e7739b434d1c62f4b7e321cd530/net/http/http_cache_transaction.cc#L3096) is true).

**Comment by MichelleSNG20** [comment]
I am using cypress 7.1 and facing this invalid certificate issue.

Should I take this as solution "Maybe inform that this problem can be resolved by importing CypressProxyCA from cy/production/proxy/certs to the Trusted Root Certification Authority store"

Can anyone please advise how to access this 'cy/production/proxy/certs'?  thanks

**Comment by valter11111** [comment]
I agree with the original post, this is not only the cosmetic problem. Chromium browsers also block webRTC access (media devices are disabled) if there is "Not secure" connection.

**Comment by valter11111** [comment]
@jsantha 
> 2. Maybe inform that this problem can be resolved by importing `CypressProxyCA` from `cy/production/proxy/certs` to the Trusted Root Certification Authority store

I tried this solution, but certificate 
![image](https://user-images.githubusercontent.com/39736557/119087842-6e6fdd00-ba10-11eb-8e4f-bbcb101c82e1.png)

But chrome still suggests its "Not secure" connection.
![image](https://user-images.githubusercontent.com/39736557/119088015-a414c600-ba10-11eb-8fe4-0377cdcc378e.png)

**Comment by jsantha** [comment]
@valter11111 
I've just tried this workaround again for latest cypress version and it still works, follow these steps:

- import `AppData/Roaming/Cypress/cy/production/proxy/certs/ca.pem`
- restart chrome (check for no background chrome processes in task manager)
- run tests again and invalid cert warning should disappear

**Comment by sara444** [comment]
> @valter11111 I've just tried this workaround again for latest cypress version and it still works, follow these steps:
> 
> * import `AppData/Roaming/Cypress/cy/production/proxy/certs/ca.pem`
> * restart chrome (check for no background chrome processes in task manager)
> * run tests again and invalid cert warning should disappear

In addition to the above steps, you also need to clear the Site Settings, Data etc using Ctrl+Shift+Delete while chrome is openned via Cypress. Otherwise, chrome keeps caching the trust (untrusted certificate) as usual.

**Comment by karlamieses** [comment]
> * AppData/Roaming/Cypress/cy/production/proxy/certs/ca.pem

how can I import `AppData/Roaming/Cypress/cy/production/proxy/certs/ca.pem` @valter11111

**Comment by flotwig** [comment]
This should no longer be an issue on the latest version of Cypress, is anyone experiencing this on 10.1.0?

**Comment by karlamieses** [comment]
> This should no longer be an issue on the latest version of Cypress, is anyone experiencing this on 10.1.0?

I having the following issue with Cypress latest versions when running in the CI, I thought this is related to the issue we are talking here, what do you think?

```
[1119:0616/211249.791930:ERROR:cert_verify_proc_builtin.cc(681)] CertVerifyProcBuiltin for dashboard.stripe.com failed:
--
620 | ----- Certificate i=0 (OU=Cypress Proxy Server Certificate,O=Cypress Proxy CA,L=Internet,ST=Internet,C=Internet,CN=dashboard.stripe.com) -----
621 | ERROR: No matching issuer found
```

**Comment by shammlo** [comment]
@flotwig, my Cypress version is ` "cypress": "^10.8.0",` and im still having this error, still receiving "Not secure".

**Comment by andrii-lundiak** [comment]
I've recently migrated from Cypress `v7.x` to `v9.7.0` and this issue (`ERROR: No matching issuer found`) happens on my CI only (Azure, Ubuntu). Sometimes it's NOT happening. 

I read a few threads and it seems issue was fixed in `v10.2.0` which I anticipate to upgrade yet. @MichaelDimmitt refers here: https://github.com/cypress-io/cypress/discussions/22128

But I also see that @shammlo refers above to `v10.8.0` as also not working version. 

@jsantha, as author of this issue which is still open in Jan-2023, how about you?

**Comment by awerlang** [comment]
@flotwig @karlamieses @andrii-lundiak I believe the issue you have in mind is unrelated (`ERROR: No matching issuer found`)

If Cypress could import the `ca.pem` file automatically, it would improve the experience running on the cloud.

**Comment by amenk** [comment]
* Would it work to deploy an own valid certificate via https://docs.cypress.io/guides/references/client-certificates or does client certificates really mean client here and has no effect on the cypress proxy-server?
* What is the path of AppData/Roaming/Cypress/cy/production/proxy/certs/ca.pem on Linux?
** EDIT: it's `~/.config/Cypress/cy/production/proxy/certs/ca.pem`
* It can be imported at chrome://settings/certificates -> Authorities in any chrome instance (it seems to be globally trusted than even Cypress uses another User Profile)
* I can confirm that importing that certificate solves the cache Problems in Cypress with Chrome 113

**Comment by nagash77** [comment]
Are folks on this thread still experiencing this issue on the latest version of Cypress?

**Comment by amenk** [comment]
We see the issue in Cypress 12.11.0

**Comment by martin-pikalek** [comment]
Importing CA certificate solved caching issue for me for local testing but could someone help me, how could I import same certificate in CICD within cypress docker image environment? 

Also could be this solved somehow globally within cypress app @jennifer-shehane ? Seems that this issue is known for nearly 3 years and disabled disk cache may quite hard affect testing speeds for apps where developers intentionally utilise browser client cache to speed up loading of assets and reduce HTTP traffic.

**Comment by amenk** [comment]
@martin-pikalek maybe something like this could work https://thomas-leister.de/en/how-to-import-ca-root-certificate/
And yes, it would be good if this would be in the `cypress/browsers` docker images.

**Comment by amenk** [comment]
The Chrome Cert file to import to seems to be `/root/.pki/nssdb/cert9.db` I am wondering if Cypress' ca.pem is always generated freshly and we need to import it after running cypress the first time or we could incude it statically in the Docker image.

EDIT: I am trying to prepend something like this to my run command:

```
        - docker-compose run cypress "yarn cypress install && apt update && apt install -y libnss3-tools && certutil -A -n Cypress -t 'TCu,Cu,Tu' -i /root/.config/Cypress/cy/production/proxy/certs/ca.pem -d sql:/root/.pki/nssdb/ && yarn cypress run --browser $BROWSER --spec cypress/e2e/index.cy.js"
```

but getting

certutil: function failed: SEC_ERROR_BAD_DATABASE: security library: bad database.

Also we might need to run cypress with an empty spec at first to generate the pa.pem

EDIT2: I have to remove the file name 

```-d sql:/root/.pki/nssdb``` works

**Comment by amenk** [comment]
That's the final command we use as a workaround in our CI:

```
      - $COMPOSE_CMD run cypress bash -c "yarn cypress install && touch cypress/e2e/empty.cy.js && yarn cypress run --browser $BROWSER --spec cypress/e2e/empty.cy.js || true && apt update && apt install -y libnss3-tools && certutil -A -n Cypress -t 'TCu,Cu,Tu' -i /root/.config/Cypress/cy/production/proxy/certs/ca.pem -d sql:/root/.pki/nssdb && yarn cypress run --browser $BROWSER --spec $SPEC"
```

Are there chances to add an option `--auto-import-ca` to cypress  ?

**Comment by marktnoonan** [comment]
Glad you got a work around @amenk! `--auto-import-ca` seems like a good idea to me, would you mind opening a feature request issues linking back to this comment and the other context in this thread? It will help keep the request separate from the longer conversation in this issue.

**Comment by amenk** [comment]
Okay, can be followed up in https://github.com/cypress-io/cypress/issues/26744 then

**Comment by AtofStryker** [comment]
Reopening this: the report was correct and the original close didn't reflect that. The "certificate error is purely cosmetic" framing in our docs was wrong — Chrome disables the HTTP disk cache for any response with a certificate error, so the app under test genuinely didn't behave the way it does in production.

I re-verified this month: on the proxy path, zero AUT URLs reach Chrome's disk cache; running the same plain-HTTP site through the same proxy caches fine — so the proxy wasn't the problem, the Cypress-signed cert was, exactly as reported here.

#34633 fixes this in Cypress 16: Chrome, Chromium, and Edge get the origin's real certificate by default because Cypress no longer terminates TLS for browser traffic, and disk caching behaves normally. Firefox and WebKit still use the proxy path, so this qualification stays until they have an equivalent.

This issue will close when #34633 lands.
