### ISSUE TITLE
Unable to open my corporate application using cypress

### ISSUE THREAD

**Issue by VinothArasu** [cypress-io/cypress#7735]
HI, I'm facing issue, While i try to access my corporate application.

![issue1](https://user-images.githubusercontent.com/53971556/84860039-f1174c00-b08b-11ea-9d08-a83360ac1ed4.png)

i have set the proxy based on my corporate account.

![issue1 1](https://user-images.githubusercontent.com/53971556/84860085-02605880-b08c-11ea-966e-75fa3324327f.png)

**Comment by jennifer-shehane** [comment]
Could you run Cypress in [debug mode](https://on.cypress.io/troubleshooting#Print-DEBUG-logs) mode and print the entire set of logs here?

**Comment by VinothArasu** [comment]
![image](https://user-images.githubusercontent.com/53971556/85064393-21b0d000-b1c9-11ea-8d1d-fdf28fd91330.png)


session::::::::::::::::::undefined
chrome-extension://mheiphfcfdhlkecdhpgblhpemkecaheh/common.js:38 SSO extension (frame https://aqr.dok-re7.intra.renault.fr/aqr/#/login)
chrome-extension://mheiphfcfdhlkecdhpgblhpemkecaheh/common.js:38 page loaded
chrome-extension://mheiphfcfdhlkecdhpgblhpemkecaheh/common.js:38 starting
/aqr/webpackdependency/jsbuild/musesappbundle.1592475131288.js:1 session::::::::::::::::::undefined
/aqr/webpackdependency/jsbuild/angularbundle.1592475131288.js:1 Request succeeded>>
/aqr/webpackdependency/jsbuild/angularbundle.1592475131288.js:1 finally finished server callback
/__/#/tests/integration\examples\Muses.js:1 A cookie associated with a cross-site resource at http://renault.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
/__/#/tests/integration\examples\Muses.js:1 A cookie associated with a cross-site resource at https://idp2.renault.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
/__/#/tests/integration\examples\Muses.js:1 Refused to display 'https://idp2.renault.com/nidp//app/login?target=https%3A%2F%2Fidp2.renault.com%3A8443%2Fnidp%2Foauth%2Fnam%2Fauthz%3Fresponse_type%3Did_token%2Btoken%26acr_values%3Dsecure%2Fname%2Fpassword%2Furi%26state%3D_UjfRYqu9A2zfVBTW36WL7ABIcpXOI2Mfbu-1dUZ8C8%26nonce%3DnmIUAy0rZQm-BUcxD_kUszSxbDLrWX1Ix4o72D0LJis%26scope%3Dopenid%2BarcaX%26client_id%3D7a88a38c-b790-4690-a529-54ab7127c451%26redirect_uri%3Dhttps%3A%2F%2Faqr.dok-re7.intra.renault.fr%2Faqr%2Fopenid_callback.html%26resourceServer%3DIdentityProvider&id=FormLogin-Intranet&forceAuth=true' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
DevTools failed to load SourceMap: Could not load content for https://aqr.dok-re7.intra.renault.fr/__cypress/runner/popper.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by VinothArasu** [comment]
Hi , Is this fine?

**Comment by VinothArasu** [comment]
HI, Any update on this.

Thanks in advance

**Comment by jennifer-shehane** [comment]
We have a potential fix available for this starting in [`4.6.0`](https://docs-staging.cypress.io/guides/references/changelog.html#4-6-0) as an [experiment](https://on.cypress.io/experiments).Can you try setting this config option in your `cypress.json` or elsewhere:

```json
{
	"experimentalSourceRewriting": true
}
```

**Comment by jennifer-shehane** [comment]
Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

**Comment by marcelogpaulo** [comment]
> Since this issue hasn't had activity in a while, we'll close the issue until we can confirm this is still happening. Please comment if there is new information to provide concerning the original issue and we'd be happy to reopen.

Hi there,

Im having the same issue and it's happening quite often.
Cypress version 6.5.0

DevTools failed to load SourceMap: Could not load content for https://##########.com.br/__cypress/runner/popper.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

i have already set this "experimentalSourceRewriting": true and the error still happens.

**Comment by pirasanthan-jesugeevegan-tes** [comment]
Any fix for this issue?

**Comment by sagarsonarnitor** [comment]
Any fix for above mentioned issue

**Comment by pmcg86** [comment]
Any fix for this?
