### ISSUE TITLE
Cypress.on('uncaught:exception') receives CypressError instead of thrown error

### ISSUE THREAD

**Issue by vicrep** [cypress-io/cypress#8418]
### Current behavior:

This might be a regression with Cypress 5.0.

I have a global catch for `ResizeObserver loop limit exceeded` in my `support/index.js` file.

```js
const resizeObserverLoopErrRe = /^ResizeObserver loop limit exceeded/

Cypress.on('uncaught:exception', err => {
  if (resizeObserverLoopErrRe.test(err.message)) {
    return false
  }
})
```

As of version 5, I started noticing that when this error occurs, the handler will receive a `CypressError` instance, instead of the original error containing the above message. This therefore makes the tests fail, and returns the usual info message about this error:

```

The following error originated from your application code, not from Cypress.

  > ResizeObserver loop limit exceeded

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

https://on.cypress.io/uncaught-exception-from-application
``` 

### Desired behavior:

The handler should receive the actual globally thrown error, as it previously did.

### Test code to reproduce

https://github.com/vicrep/cypress-test-tiny/pull/1/files

### Versions

Cypress: 5.0.0
Browser: Both on Electron and Chrome (didn't test others)
OS: Reproed on macOS and Linux

**Comment by jennifer-shehane** [comment]
We changed how the errors are constructed in 4.6.0+, you'll need to upgrade your Regex to match the newly constructed error:

```js
const resizeObserverLoopErrRe = /^[^(ResizeObserver loop limit exceeded)]/
Cypress.on('uncaught:exception', (err) => {
    /* returning false here prevents Cypress from failing the test */
    if (resizeObserverLoopErrRe.test(err.message)) {
        return false
    }
})
```

**Comment by vicrep** [comment]
Thanks for the prompt reply @jennifer-shehane , and for the mitigation steps. :)

I wasn't able to find any reference to this change in changelog, and the docs don't make this explicit (and the type-hints still say the error is of type `Error`, not `CypressError`). Could I suggest this change be documented somehow to avoid people running into similar issues in future?

**Comment by malykhinvi** [comment]
@jennifer-shehane thanks for the answer! But the solution is not completely clear to me. Could you please elaborate why this regexp is more suitable in that case. In particular, I can not get my head around the solution, because of that example:
```
resizeObserverLoopErrRe.test('ResizeObserver loop limit exceede') // false
resizeObserverLoopErrRe.test('anything else') // true
```

**Comment by MatiDiez** [comment]
Hey @jennifer-shehane or anyone. I've implemented this"ignore" command and the result is that the error doesn't appear in red anymore on the cypress runner but I have some sort of follow up problem. The test run never ends as this error keeps piling up and appearing over and over. 

This not only causes this to never end, but it starts killing my memory and the runner becomes unusably slow. Any ideas? Is this a different issue?

![image](https://user-images.githubusercontent.com/8494526/120829796-31d5d280-c534-11eb-86ab-80ddca5b0913.png)

**Comment by jennifer-shehane** [comment]
@MatiDiez Oh, very interesting, this is not something we considered. 🤔  It'd be great if you could provide a reproducible example and open a new issue. I'll try to see if I can recreate.

**Comment by MatiDiez** [comment]
Hey @jennifer-shehane unfortunatelly I don't have access to share that example. The only condition to reproduce it was that when I got that execption using the test runner, and test runner was still opened in the same spec, it kept tryin to execute that. This will only happen if it is the last test or if the test failed and the runner goes back to focus that sequence.

**Comment by Zeioth** [comment]
> We changed how the errors are constructed in 4.6.0+, you'll need to upgrade your Regex to match the newly constructed error:
> 
> ```js
> const resizeObserverLoopErrRe = /^[^(ResizeObserver loop limit exceeded)]/
> Cypress.on('uncaught:exception', (err) => {
>     /* returning false here prevents Cypress from failing the test */
>     if (resizeObserverLoopErrRe.test(err.message)) {
>         return false
>     }
> })
> ```

Still shows the message, just as a normal message, instead of an error (red color). Would be cool having a way to silence it completely.

**Comment by hon2a** [comment]
@jennifer-shehane Please note that the regular expression you posted actually matches "any text starting with a character that is not one of `() ORcdeilmoprstvxz`" (all characters present in `(ResizeObserver loop limit exceeded)`), which is patently wrong and causes a lot of other errors to be possibly swallowed.

**Comment by alineborak** [comment]
I'm facing similar problem, however the solution proposed by @jennifer-shehane did nothing to ignore the error, it keeps happening.
Then I tried instead what @hon2a proposed above, but when I add that instead to my support/index.js, I get the following cors error:

![Screenshot 2022-03-29 at 14 33 18](https://user-images.githubusercontent.com/36476341/160612103-bfcd3ad1-52af-4410-aff7-022bafee7480.png)



I'm using cypress version 9.4.1

Can someone help please?

**Comment by justinpincar** [comment]
Using `cy.viewport` in multiple tests in the same file caused this issue for me; moving it to a `before` hook sidestepped it.

@alineborak Your error is different than the `ResizeObserver` one, so you would need to change the regex to look for `Script error`. Or better, don't include the NewRelic tracker in your test env.

**Comment by willoliveira-air** [comment]
I started to see the same issue after upgrading to version 10.2.
Even using the workaround from @jennifer-shehane [jennifer-shehane](https://github.com/jennifer-shehane)

```
const resizeObserverLoopErrRe = /^[^(ResizeObserver loop limit exceeded)]/
Cypress.on('uncaught:exception', (err) => {
    /* returning false here prevents Cypress from failing the test */
    if (resizeObserverLoopErrRe.test(err.message)) {
        return false
    }
})
```

Any ideas? Thanks

**Comment by danfooks** [comment]
> I started to see the same issue after upgrading to version 10.2. Even using the workaround from @jennifer-shehane [jennifer-shehane](https://github.com/jennifer-shehane)
> 
> ```
> const resizeObserverLoopErrRe = /^[^(ResizeObserver loop limit exceeded)]/
> Cypress.on('uncaught:exception', (err) => {
>     /* returning false here prevents Cypress from failing the test */
>     if (resizeObserverLoopErrRe.test(err.message)) {
>         return false
>     }
> })
> ```
> 
> Any ideas? Thanks

I am having the same issue after upgrading to `10.0.2` as well @willoliveira-air @jennifer-shehane . Below is my configuration:
```
Cypress.on('uncaught:exception', (err) => {
  // returning false here prevents Cypress from
  // failing the test
  cy.log('Cypress detected uncaught exception: ', err);
  console.log('Cypress detected uncaught exception: ', err);
  return false;
});
```

While the `cy.log` and `console.log` statements are working as expected, it seems that Cypress can no longer ignore exceptions.

**Comment by danfooks** [comment]
I also created a fresh bug ticket to shed some light on the issue, as this bug pertains to a newer version of Cypress:
https://github.com/cypress-io/cypress/issues/22129

**Comment by mb73** [comment]
I noticed that after upgrading from Cypress 9 to 10, my IDE complained about the `includes` statement and suggested to increase `lib` from `es5` to `es6` in `cypress/tsconfig.json`, which I did. After also [restarting the TS server](https://stackoverflow.com/questions/64454845/where-is-vscodes-restart-ts-server), the error disappeared. Not sure if this is relevant here, though.

**Comment by dannylistSR** [comment]
> Using `cy.viewport` in multiple tests in the same file caused this issue for me; moving it to a `before` hook sidestepped it.
> 
> @alineborak Your error is different than the `ResizeObserver` one, so you would need to change the regex to look for `Script error`. Or better, don't include the NewRelic tracker in your test env.

I was having the same issue. Moved my viewport command into a `before` rather than a `beforeEach` and it's all working fine.
