### ISSUE TITLE
The Chinese characters in the Cypress console log show garbled code

### ISSUE THREAD

**Issue by takeoffclothes** [cypress-io/cypress#9039]
![image](https://user-images.githubusercontent.com/42593169/97676513-bc041700-1acb-11eb-9054-c45b0b778c08.png)

**Comment by jennifer-shehane** [comment]
When opening an issue, please fill out the [bug report template](https://github.com/cypress-io/cypress/blob/develop/.github/ISSUE_TEMPLATE/bug-report.md) provided - it requires necessary information we need to help you, like desired behavior, a reproducible example and the version of Cypress you are using to help us better address your issue. 

We've fixed several issues with foreign characters display in the Command Log, so likely this is specific to the characters used. Please provide the characters that are not displaying.

This issue will be closed per our [contributing guidelines](https://github.com/cypress-io/cypress/blob/develop/.github/CONTRIBUTING.md#does-the-issue-provide-all-the-information-from-our-issue-template). Please comment in this issue with the required information from our issue template and we'll be happy to reopen the issue.

**Comment by takeoffclothes** [comment]
The cyPress version used is 5.4.0.
I'm working on an exercise: connect to a mysql database using Cypress's cy-exec () command.The result of this instance is a response to a student's ID and name.The name is in Chinese.
the code like this:
describe('执行系统命令查询sql', function() {
    beforeEach(() => {
        cy.exec("python D:\\small99\\cypress_primary\\cypress_primary\\cypress\\fixtures\\executeSql.py")
            .as("get_result")
            .then(function(result) {
                // json解析成object
                // const res_body = JSON.parse(result.stdout[0]);
                const res_body = result.stdout;
                //  示例：打印出来，期望值 ：测-生321
                cy.log(res_body);
                // 断言 返回结果
                expect(res_body.length).to.be.at.least(1)
            }
            )

    });

**Comment by jennifer-shehane** [comment]
I haven't been able to get an exact example that doesn't log out the characters. Can you provide an example that I can fully run without the python script that would show the issue?

I'm not sure if you are running this locally or on a CI machine, but you'll need to ensure that the machine has the Chinese fonts included so that they display properly also.

```js
describe('执行系统命令查询sql', function () {
  it('test', () => {
    cy.fixture('chinese').then((json) => {
      cy.log(json)
    })
  })
})
```

<img width="557" alt="Screen Shot 2020-11-03 at 11 50 56 AM" src="https://user-images.githubusercontent.com/1271364/97952406-af353b00-1dcb-11eb-95b0-197ce19ea66a.png">


```js
describe('执行系统命令查询sql', function () {
  it('test', () => {
    const json = '{"id": 1234, "name": "示例：打印出来，期望值 ：测-生321"}';
    const res_body = JSON.parse(json);
    cy.log(res_body)
  })
})
```

<img width="736" alt="Screen Shot 2020-11-03 at 11 56 22 AM" src="https://user-images.githubusercontent.com/1271364/97952403-a47aa600-1dcb-11eb-8d93-81198f1c4bfc.png">

**Comment by takeoffclothes** [comment]
Thank you very much for your attention and reply
The problem is still unresolved, but I've located the exact location where it went wrong.
The key is the stdout of cy. Exe ().
Using the following example, a garbled code appears on the console.
describe('执行系统命令', function() {
    it("输出内容为中文", ()=>{
        cy.exec("echo 中文")
            .as("get_result")
        cy.get('@get_result').then((output)=>{
            const response = output.stdout
            cy.log(response)
        });

    });
});

**Comment by jennifer-shehane** [comment]
I'm still not able to reproduce this. 

What machine are you running your tests on? Is this locally or in CI? A docker container?

`cypress open`

<img width="430" alt="Screen Shot 2020-11-04 at 12 55 46 PM" src="https://user-images.githubusercontent.com/1271364/98076773-51712380-1e9d-11eb-8c03-85a09d54e874.png">

`cypress run`

<img width="452" alt="Screen Shot 2020-11-04 at 12 56 36 PM" src="https://user-images.githubusercontent.com/1271364/98076786-57ff9b00-1e9d-11eb-896e-3b12efc37546.png">

**Comment by takeoffclothes** [comment]
just cypress open
I guess it has to do with my NodeJS configuration

**Comment by takeoffclothes** [comment]
I'm glad to see you have a normal display here
My environment is like this:
64-bit Windows 7,
The Node version is V12.16.0.Use the .MSI file type installation
does not use Docker,
The results of the Cypress Open run show garbled code
Can you tell me about your environment configuration
